var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,e){a!=Array.prototype&&a!=Object.prototype&&(a[b]=e.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,b,e,c){if(b){e=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var f=a[c];f in e||(e[f]={});e=e[f]}a=a[a.length-1];c=e[a];b=b(c);b!=c&&null!=b&&$jscomp.defineProperty(e,a,{configurable:!0,writable:!0,value:b})}};$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;
$jscomp.Symbol=function(a){return $jscomp.SYMBOL_PREFIX+(a||"")+$jscomp.symbolCounter_++};$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};
$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};
$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var e=0,c={next:function(){if(e<a.length){var f=e++;return{value:b(f,a[f]),done:!1}}c.next=function(){return{done:!0,value:void 0}};return c.next()}};c[Symbol.iterator]=function(){return c};return c};$jscomp.polyfill("Array.prototype.entries",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a,e){return[a,e]})}},"es6-impl","es3");var hi5=hi5||{};
hi5.init={inited:!1,funcs:[],push:function(a){hi5.init.funcs.push(a)},start:function(a){if(!hi5.init.inited){hi5.browser.innerHeight=window.innerHeight;hi5.init.inited=!0;a=hi5.init.funcs;for(var b=0,e=a.length;b<e;b++)a[b]();hi5.init.release()}},release:function(){document.removeEventListener("DOMContentLoaded",hi5.init.start,!1)}};
window.requestAnimationFrame||(window.requestAnimationFrame=window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,30,Date.now())});window.URL=window.URL||window.webkitURL;window.WebSocket=window.WebSocket||window.MozWebSocket;hi5.WebSocket=window.WebSocket;hi5.$=function(a){return document.getElementById(a)};
hi5.html={hasClass:function(a,b){return a.classList.contains(b)},addClass:function(a,b){a.classList.add(b)},removeClass:function(a,b){a.classList.remove(b)}};
hi5.browser=new function(){var a=navigator.userAgent;this.innerHeight=0;this.isEdge=-1!=a.indexOf("Edge");var b=(this.isIE=-1!=a.indexOf("MSIE")||-1!=a.indexOf("Trident"))||this.isEdge;this.isTouch="maxTouchPoints"in navigator||"msMaxTouchPoints"in navigator?1<=(navigator.msMaxTouchPoints||navigator.maxTouchPoints):"ontouchstart"in window||"createTouch"in document||"DocumentTouch"in window&&window.document instanceof window.DocumentTouch||-1!=a.indexOf("Mobile");this.isFirefox=-1!=a.indexOf("Firefox")&&
!b;this.isOpera=-1!=a.indexOf("Opera");this.isRIM=-1!=a.indexOf(" RIM ");this.isChrome=-1!=a.indexOf("Chrome")&&!b;this.isMacOS=-1!=a.indexOf("Mac OS");this.isWindows=-1!=a.indexOf("Windows ");this.isiOS=navigator.userAgent.match(/(iPad|iPhone|iPod)/i)?!0:!1;this.isSafari=-1==a.indexOf("Chrome")&&-1!=a.indexOf("Safari")&&!b;this.isWebKit=-1!=a.indexOf("WebKit");this.isCrOS=-1!=a.indexOf("CrOS");this.isOperaNext=-1!=a.indexOf("Edition Next");this.isAndroid=-1!=a.indexOf("Android");this.isChromeApp=
"chrome"in window&&"app"in chrome&&"window"in chrome.app;this.isDesktop=!a.match(/(iPhone|iPod|iPad|Android|BlackBerry|Mobile)/);this.isLinux=-1!=a.indexOf("Linux");this.isElectron=!!(window.process&&process.versions&&process.versions.electron);b=window.outerHeight-window.innerHeight;this.isMetro=0==window.screenY&&(0==window.screenX||window.screenX+window.outerWidth==screen.width)&&3<b&&31>b;this.isMultitask=!(this.isiOS&&this.isSafari&&0<a.indexOf("Version/5"));this.binaryWS=function(){return hi5.browser.isChrome?
!0:hi5.tool.hasProperty(WebSocket,"binaryType")};this.cookie2Obj=function(){var a=document.cookie,f={};if(""==a)return f;for(var d=a.split(";"),b=0,e=d.length;b<e;b++){for(var l=d[b];" "==l.charAt(0);)l=l.substring(1,l.length);a=l.indexOf("=");if(0<a){var k=decodeURIComponent(l.substring(a+1).replace(/\+/g," "));hi5.tool.isNumber(k)&&"0"!=k[0]&&parseFloat(k)==k&&(k=parseFloat(k));if("true"==k||"on"==k)k=!0;else if("false"==k||"off"==k)k=!1;f[l.substring(0,a)]=k}}return f};this.obj2url=function(a){var c=
"",d;for(d in a)c+="&"+d+"=",c="boolean"==typeof a[d]?c+(a[d]?"on":"off"):c+encodeURIComponent(a[d]);c&&(c=c.substring(1));return c};this.getLibPath=function(a){for(var c=document.getElementsByTagName("script"),d,b,e="",l=c.length,k=0;k<l;k++)if(b=c[k].src,d=b.indexOf(a),-1<d){e=b.substring(0,d);break}0==e.indexOf(location.origin)&&(e=e.substring(location.origin.length));return e};this.loadJS=function(a,b){0>a.indexOf("/")&&(a=hi5.libPath+a);if(!hi5.browser.getLibPath(a)){var d=document.createElement("script");
d.type="text/javascript";d.src=a;b&&(d.onload=b,d.onreadystatechange=function(){"complete"==this.readyState&&b()});(document.body||document.getElementsByTagName("script")[0].parentNode).appendChild(d)}};this.formToObj=function(a,b){var d=a.elements,c,f=d.length;b||(b={});for(var e=0;e<f;e++){var k=d[e];if(c=k.name){var m=k.type;switch(m){case "submit":case "button":case "reset":continue;case "checkbox":k=k.checked;break;case "radio":if(!k.checked)continue;k=k.value;break;case "number":parseFloat(k.value);
default:k=k.value}""!=k&&(b[c]=k)}}return b};this.objToForm=function(a,b){var d,c=b.elements,f;for(f in a)if(d=c[f]){var e=a[f];"boolean"==typeof e?d.checked=e:d.value=e}};this.objToCookie=function(a){for(var c in a)""!=a[c]&&(document.cookie=c+"="+a[c])};this.getScale=function(){return document.documentElement.clientWidth/window.innerWidth};this.httpGet=function(a,b){var d=new XMLHttpRequest;d.open("GET",a,b);d.withCredentials=!0;d.setRequestHeader("Content-Type","text/plain;charset=UTF-8");d.send(null);
return d.responseText};this.selectEditable=function(a){try{var c=document.createRange();c.selectNodeContents(a);var d=window.getSelection();d.removeAllRanges();d.addRange(c)}catch(g){console.log(g)}};this.setOrientaionHandler=function(a){"onorientationchange"in screen?screen.onorientationchange=a:"onmozorientationchange"in screen?screen.onmozorientationchange=a:"onmsorientationchange"in screen?screen.onmsorientationchange=a:window.addEventListener("orientationchange",a,!1)};var e={x:0,y:0};this.getMousePos=
function(a,b){var d=(b||a.target).getBoundingClientRect();e.x=a.clientX-d.left;e.y=a.clientY-d.top;return e};this.calMousePos=function(a,b,d){d=d.getBoundingClientRect();e.x=a-d.left;e.y=b-d.top;return e};this.getHost=function(){var a=hi5.tool.queryToObj().gateway;if(!a&&!hi5.browser.isChromeApp)if(a=location.host){var b=location.pathname,d=b.indexOf("://");0<d&&(a+=b.substring(0,b.indexOf("/",d+3)))}else a="localhost";return a};this.html2text=function(a){var c=document.createElement("div");c.innerHTML=
a.replace(/<style([\s\S]*?)<\/style>/g,"");return c.textContent.replace(/\r?\n/g,"\r\n").replace(RegExp("\u00a0","g")," ")};this.dataURLtoBlob=function(a){var b=a.indexOf(","),d=a.substring(0,b++),c=d.indexOf(":"),e=d.indexOf(";",c),e=e>c?d.substring(c+1,e):"text/plain";a=0<d.indexOf("base64",c)?hi5.Base64.dec(a,b,!0):a.substring(b);return new Blob([a],{type:e})};this.loadFlash=function(a,b,d,e,h){e=e||8;h=h||8;d=d||"__sv_flash_plugin";b=b||document.body;var c=document.getElementById(d);if(c)return c;
var c=document.createElement("div"),f=c.style;f.position="fixed";f.width=f.height=e+"px";f.bottom=f.left=h+"px";f.overflow="hidden";f.opacity=0;c.innerHTML='<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" type="application/x-shockwave-flash" data="'+a+'" width="'+e+'" height="'+h+'" id="'+d+'"><param name="allowScriptAccess" value="always" /></object>';b.appendChild(c);return c.childNodes[0]};this.getScreenWidth=function(){if(-1==navigator.userAgent.indexOf("MSIE")&&-1==navigator.userAgent.indexOf("Trident")||
0<=window.screenX&&window.screenX<screen.width&&0<=window.screenY&&window.screenY<screen.height)return screen.width;for(var a=window.outerWidth,b=[1920,2560,3840,4E3,7680],d=0;5>d;d++)if(a<=b[d])return b[d];return a};this.getScreenHeight=function(){if(-1==navigator.userAgent.indexOf("MSIE")&&-1==navigator.userAgent.indexOf("Trident")||0<=window.screenX&&window.screenX<screen.width&&0<=window.screenY&&window.screenY<screen.height)return screen.height;for(var a=window.outerHeight,b=[1080,1200,1600,
2E3,2160,4320],d=0;5>d;d++)if(a<=b[d])return b[d];return a};this.cookie={set:function(a,b,d){var c=new Date;c.setTime(c.getTime()+864E5*d);d="expires="+c.toUTCString();document.cookie=a+"="+b+";"+d+";path=/"},get:function(a){a+="=";for(var b=decodeURIComponent(document.cookie).split(";"),d=0;d<b.length;d++){for(var c=b[d];" "==c.charAt(0);)c=c.substring(1);if(0==c.indexOf(a))return c.substring(a.length,c.length)}return""},"delete":function(a){document.cookie=a+"=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;"}}};
hi5.libPath||(hi5.libPath=hi5.browser.getLibPath("hi5core.js")||hi5.browser.getLibPath("hi5.js"),hi5.libPath?hi5.libMin=!1:(hi5.libPath=hi5.browser.getLibPath("hi5core_min.js")||hi5.browser.getLibPath("hi5_min.js"),hi5.libPath&&(hi5.libMin=!0)));
hi5.storage=new function(){function a(a,b){this._state=b||0;this._value=a}function b(a){return a&&0==a.indexOf("{")&&(a=JSON.parse(a))&&"_state"in a&&"_value"in a?a:null}var e="chrome"in window&&!!chrome.storage,c="localStorage"in window;if(c)try{localStorage.setItem("_t_s_t","1"),localStorage.removeItem("_t_s_t")}catch(d){c=this.isAvailable=!1}this.isAvailable=!!e||c;var f=e||!this.isAvailable?{}:localStorage;e&&chrome.storage.local.get(null,function(a){for(var b in a)f[b]=a[b]});this.set=function(b,
c){f[b]=JSON.stringify(new a(c,1))};this.get=function(a){a=f[a];var d=b(a);return d?d._value:a};this.clear=function(a){f={};e?chrome.storage.local.clear(a||function(){}):c&&localStorage.clear()};this.remove=function(a){if(f.removeItem)f.removeItem(a);else{var c=b(f[a]);c&&(c._state=2,f[a]=JSON.stringify(c))}};this.commit=function(a){a=a||function(){};if(e){var c={},d=[],l=!1,k;for(k in f){var m=b(f[k]);m&&(1==m._state?(c[k]=m._value,l=!0):2==m._state&&d.push(k))}0<d.length&&chrome.storage.local.remove(d,
function(){for(var b=0,c=d.length;b<c;b++)delete f[d[b]];a&&a()});l&&chrome.storage.local.set(c,a)}else a()}};
hi5.tool={isNumber:function(a){return!isNaN(parseFloat(a))&&isFinite(a)},cumulativePos:function(a){var b=0,e=0;do if(b+=a.offsetTop||0,e+=a.offsetLeft||0,b+=parseInt(a.style.borderLeftWidth)||0,e+=parseInt(a.style.borderTopWidth)||0,b-=a.scrollTop,e-=a.scrollLeft,a=a.offsetParent,a==document.body)break;while(a);return{x:e,y:b}},getPos:function(a,b){var e=0,c=0;do{if(b&&"static"!=getComputedStyle(a).getPropertyValue("position"))break;e+=a.offsetLeft;c+=a.offsetTop}while(a=a.offsetParent);return{x:e,
y:c}},bytesToSize:function(a){if(isNaN(a))return"";var b=Math.floor(Math.log(+a)/Math.log(2));1>b&&(b=0);b=Math.floor(b/10);a=+a/Math.pow(2,10*b);a.toString().length>a.toFixed(3).toString().length&&(a=a.toFixed(2));return a+" bytes; KB; MB; GB; TB; PB; EB; ZB; YB".split(";")[b]},queryToObj:hi5.string.queryToObj,replaceQuery:function(a,b,e){var c=a.indexOf(b+"="),f=!1;0<c&&(c=a.charAt(c-1),"&"==c||"?"==c)&&(f=!0);return f?a.replace(new RegExp("[\\?&]"+b+"=([^&#]*)"),function(a){return a.charAt(0)+
b+"="+encodeURIComponent(e)}):a+="&"+b+"="+encodeURIComponent(e)},disableInput:function(a){window.__hi5_bk&&hi5.tool.enableInput();var b=document.createElement("div");if(a){var e=window.getComputedStyle(a);b.style.position=e.getPropertyValue("position");b.style.left=e.getPropertyValue("left");b.style.top=e.getPropertyValue("top");b.style.width=e.getPropertyValue("width");b.style.height=e.getPropertyValue("height");b.style.zIndex=e.getPropertyValue("zIndex");b.style.right=e.getPropertyValue("right");
b.style.bottom=e.getPropertyValue("bottom")}else b.style.position="fixed",b.style.left=0,b.style.top=0,b.style.width="100%",b.style.height="100%",b.style.zIndex=99999;b.style.background="url("+hi5.libPath+"spinner.gif) no-repeat center center";a?a.parentNode.appendChild(b):document.body.appendChild(b);window.__hi5_bk=b},enableInput:function(){window.__hi5_bk&&(window.__hi5_bk.parentNode.removeChild(window.__hi5_bk),window.__hi5_bk=null)},scale:function(a,b,e,c,f){c=void 0===c?"left top":c+" "+f;e||
(e=b);a.style.transformOrigin=c;a.style.MozTransformOrigin=c;a.style.webkitTransformOrigin=c;a.style.msTransformOrigin=c;a.style.OTransformOrigin=c;b="scale("+b+","+e+")";a.style.transform=b;a.style.MozTransform=b;a.style.webkitTransform=b;a.style.msTransform=b;a.style.OTransform=b},openWebSocket:function(a,b,e){var c=!1;e&&(e=hi5.callback.put(e),a+="&callback="+e);var f=new WebSocket(a,"ctrl");f.onopen=function(a){c=!0;b&&f.send(b)};f.onclose=function(a){c||alert("Failed to connect")};f.onmessage=
function(a){a=JSON.parse(a.data);f.close();a.callback?hi5.callback.get(a.callback)(a):console.log(a)};return f},getChildNodesByTag:function(a,b){for(var e=a.childNodes,c=[],f=0,d=e.length;f<d;f++)e[f].nodeName.toLowerCase()==b&&c.push(e[f]);return c},hasProperty:function(a,b){return b in a||b in a.prototype?!0:b in(a.__proto__||a.constructor.prototype)},isCapslock:function(a){var b=String.fromCharCode(a.keyCode||a.which);return b.toUpperCase()!=b||b.toLowerCase()==b||a.shiftKey?!1:!0},getImage:function(a,
b){b&&0!=b.indexOf("/")&&(b=hi5.libPath+b);return hi5&&hi5.appcfg&&hi5.appcfg.img?hi5.appcfg.img[a]||b:b},uuid:function(){for(var a="",b=Array(16),e,c=0;16>c;c++)switch(b[c]=255*Math.random()|0,e=b[c].toString(16),1==e.length&&(e="0"+e),c){case 3:case 5:case 7:case 9:a+=e;a+="-";break;case 6:a+="4"+e[1];break;case 8:a+=(parseInt(e[0],16)&3|8).toString(16)+e[1];break;default:a+=e}return a},text2html:function(a){return a.replace(/\n/g,"<br>")},Profiler:function(){function a(){this.totalTime=this.count=
0}var b={},e=0,c=null,f=!1;this.begin=function(d){if(f){c=d;var g=b[d];void 0===g&&(g=new a,b[d]=g);e=(new Date).getTime();return g}};this.end=function(a){if(f){a=b[a||c];var d=(new Date).getTime()-e;a.totalTime+=d;a.count++;return a}};this.start=function(){f||(f=!0,b={},e=0,c=null)};this.stop=function(){f&&(f=!1)};this.isStarted=function(){return f};this.print=function(){console.log(this.getResult())};this.getResult=function(a){var c={},d="undefined"===typeof a?0:a.length,e;for(e in b)0<d&&e.substring(0,
d)!==a||(c[e]=b[e]);return c}},ResponseMonitor:function(a,b){function e(){f&&(a(),d&&(c=setTimeout(b,d)))}var c=0,f=0,d;this.tag=0;this.check=function(a){f&&(clearTimeout(c),c=setTimeout(e,a||f))};this.setInterval=function(a,b){f=1E3*a|0;d=1E3*b|0};this.stop=function(){clearTimeout(c);f=0}}};navigator.getUserMedia=navigator.getUserMedia||navigator.webkitGetUserMedia||navigator.mozGetUserMedia||navigator.msGetUserMedia;
hi5.audio={recordable:!!navigator.getUserMedia||!!navigator.mediaDevices,getAudioContext:function(){var a=window.top;if(!a.AudioContext&&!a.webkitAudioContext)return null;try{a.opener&&(a.opener.AudioContext||a.opener.webkitAudioContext)&&(a=a.opener)}catch(b){}a.__audioCtx&&a.__audioCtx.state&&"running"!=a.__audioCtx.state&&(a.__audioCtx.close&&a.__audioCtx.close(),a.__audioCtx=null);a.__audioCtx||(a.__audioCtx=new (a.AudioContext||a.webkitAudioContext));a.__audioCtx.__refCount=a.__audioCtx.__refCount?
a.__audioCtx.__refCount+1:1;return a.__audioCtx},releaseAudioContext:function(){var a=window;try{window.parent!=window&&(a=window.parent)}catch(b){}a.__audioCtx&&(a.__audioCtx.__refCount&&a.__audioCtx.__refCount--,!a.__audioCtx.__refCount||1>a.__audioCtx.__refCount)&&(a.__audioCtx.close&&a.__audioCtx.close(),a.__audioCtx=null)}};hi5.audio.recordable&&(hi5.browser.isChrome||hi5.browser.isSafari)&&"https:"!=document.location.protocol&&(hi5.audio.recordable=!1);
hi5.EventControl=function(a){a.addEvent=function(b,e){a[b]&&a[b]._evt_listeners||(a[b]=function(){a.fireEvent(b,arguments)},a[b]._evt_listeners=[]);a[b]._evt_listeners.push(e)};a.removeEvent=function(b,e){if(!a[b]&&!a[b]._evt_listeners)return!1;var c=a[b]._evt_listeners,f=c.indexOf(e);return-1<f?(c.removeElm(f),!0):!1};a.fireEvent=function(b,e){if(a[b]&&a[b]._evt_listeners){var c=a[b]._evt_listeners;e||(e=[]);for(var f=0,d=c.length;f<d;f++)c[f].apply(a,e)}};return a};hi5.ui=hi5.ui||{};
hi5.ui.initAs=function(a,b){var e=a["data-h5-ui"];if(!e)return a["data-h5-ui"]=b,!0;if(-1!=hi5.string.seperatedStr.indexOf(e,b))return!1;a["data-h5-ui"]=e+","+b;return!0};hi5.ui.clean=function(a){a["data-h5-ui"]&&(a["data-h5-ui"]="")};hi5.ui.confirm=function(a){return hi5.browser.isChromeApp?!0:confirm(a)};
hi5.chromeapp={convertLink:function(a){for(var b=0,e=a.length;b<e;b++)a[b].onclick=function(a){a=a.target.href;var b=a.lastIndexOf("/");-1!=b&&(a=a.substring(b+1));chrome.app.window.create(a,{left:window.screenLeft+20,top:window.screenTop+20,width:window.innerWidth,height:window.innerHeight});return!1}}};
hi5.Draggable=function(a,b,e,c,f,d){var g,h;function l(b){n=g=!1;b.stopPropagation();b.preventDefault();var c=b.touchs||b.changedTouches;if(c){if(1!=c.length)return;b=c[0]}else if(0!=b.button)return;p=hi5.tool.getPos(a);h=b.pageX;q=b.pageY;g=!0}function k(b){if(g){var d=b.touchs&&b.touchs[0]||b.changedTouches&&b.changedTouches[0]||b;if(!(3>Math.abs(h-d.pageX)&&3>Math.abs(q-d.pageY))){n||(n=!0,e&&e(d));if(c){var f=c(d);f&&(d=f)}f=p.x+d.pageX-h;d=p.y+d.pageY-q;0>f&&(f=0);f>window.innerWidth-a.offsetWidth&&
(f=window.innerWidth-a.offsetWidth);0>d&&(d=0);d>window.innerHeight-a.offsetHeight&&(d=window.innerHeight-a.offsetHeight);a.style.left=f+"px";a.style.top=d+"px";b.stopPropagation();b.preventDefault()}}}function m(a){g&&(a.preventDefault(),a.stopPropagation(),g=!1,a=a.touchs&&a.touchs[0]||a.changedTouches&&a.changedTouches[0]||a,n?f&&f(a):d&&d(a),n=!1)}b=b||a;b.draggable=!1;if(!hi5.ui.initAs(b,"Draggable"))return b;var p=null;var q=h=0;var n=g=!1;var r=hi5.browser.isTouch;b.addEventListener("touchstart",
l,!1);b.addEventListener("mousedown",l,!1);document.addEventListener("touchmove",k,!1);document.addEventListener("mousemove",k,!1);b.addEventListener("touchmove",k,!1);b.addEventListener("mousemove",k,!1);document.addEventListener("touchend",m,!1);document.addEventListener("mouseup",m,!1);b.addEventListener("touchend",m,!1);b.addEventListener("mouseup",m,!1);r&&(document.addEventListener("touchcancel",m,!1),b.addEventListener("touchcancel",m,!1));return a};
hi5.Fadable=function(a,b,e,c){function f(){document.activeElement==a||document.activeElement==a.activeObj?setTimeout(f,k):a.style.display="none"}function d(){m&&clearTimeout(m);m=setTimeout(function(){a.beforeDisplay&&a.beforeDisplay();a.style.display=c;p&&(m&&clearTimeout(m),m=setTimeout(f,k))},88);return!1}function g(a){m&&clearTimeout(m)}function h(a){d()}if(!hi5.ui.initAs(a,"Fadable"))return a;0>a.tabIndex&&(a.tabIndex=999);var l=e||document;c=c||"block";var k=b||3E3,m=0,p=!0;a.setFadable=function(b){(p=
b)?(b="mouseup",navigator.pointerEnabled?b="pointerup":navigator.msPointerEnabled?b="MSPointerUp":hi5.browser.isTouch&&(b="touchend"),l.addEventListener(b,d,!1),l.addEventListener("mouseup",d,!1),a.addEventListener("mouseenter",g,!1),a.addEventListener("mouseleave",h,!1)):(a.style.display=c,a.removeEventListener("mouseenter",g,!1),a.removeEventListener("mouseleave",h,!1))};a.startFade=d;return a};
hi5.cancelDefault=function(a){a.preventDefault&&a.preventDefault();a.stopPropagation&&a.stopPropagation();return!1};
hi5.Toolbar=function(a,b,e){if(b){var c=(b=a.querySelector("#svImgHandle"))||document.createElement("img");b||(c.style.cursor="move",c.style.width="11px",c.src=e,c.id="svImgHandle",a.appendChild(c));hi5.Draggable(a,c)}a.addButton=function(b,c,e){var d=document.createElement("img");d.src=b;hi5.browser.isTouch?navigator.msMaxTouchPoints||d.addEventListener("touchend",c,!1):d.addEventListener("click",c,!1);d.className="h5-img-btn";a.appendChild(d);e&&(d.id=e);return d};a.getButton=function(b){for(var c=
a.getElementsByTagName("img"),e=c.length,f=0;f<e;f++)if(c[f].id==b)return c[f];return null};a.removeButton=function(b){for(var c=a.getElementsByTagName("img"),e=c.length,f=0;f<e;f++)if(c[f].id==b){a.removeChild(c[f]);break}};e=a.getElementsByTagName("img");b=e.length;for(c=0;c<b;c++)e[c].className="h5-img-btn";return a};
hi5.ProgressBar=function(a){a.progress=0;a.maxValue=0;var b=a.getElementsByTagName("div")[0];a.setProgress=function(e){e=Math.floor(e/a.maxValue*100);e!=a.progress&&(a.progress=e,b.style.width=e/100*a.offsetWidth+"px")};return a};
hi5.Lightbox=function(a,b,e,c){function f(){var b=(d.clientWidth-a.offsetWidth)/2,c=(d.clientHeight-a.offsetHeight)/3;0>b&&(b=0);0>c&&(c=0);a.style.left=b+"px";a.style.top=c+"px"}var d=document.createElement("div");d.id="divBackground";d.style.position="fixed";d.style.left=0;d.style.top=0;d.style.width="100%";d.style.height="100%";d.style.zIndex=999;d.style.backgroundColor=e?e:"#222";b||(b=.4);1>b&&(d.style.opacity=b);a.style.position="absolute";a.style.zIndex=1E3;a.style.visibility="hidden";var g=
document.createElement("img");g.width=25;g.height=25;g.src=hi5.tool.getImage("del","del.png");g.className="h5-img-btn";g.style.cursor="pointer";g.align="top";g.style.position="absolute";c?(g.style.top="-20px",g.style.right="-15px"):(g.style.top="0px",g.style.right="0px");a.resize=f;a.show=function(){document.body.appendChild(d);a.appendChild(g);a.style.display="block";a.style.visibility="visible";f();if(a.onopen)a.onopen(a)};a.visible=function(){return a&&"visible"==a.style.visibility};a.dismiss=
function(b){function c(){document.body.removeChild(d);a.removeChild(g);a.style.display="none";a.style.visibility="hidden";if(a.onclose)a.onclose()}"number"==typeof b?setTimeout(c,b):c()};a.background=d;g.addEventListener("click",a.dismiss,!1);return a};
hi5.ui.Lightbox=function(a,b){function e(){var b=(window.innerWidth-a.clientWidth)/2|0,c=(window.innerHeight-a.clientHeight)/3|0;a.style.borderWidth=c+"px "+b+"px "+2*c+"px "+b+"px"}function c(a){27==a.keyCode&&f()}function f(){var b=a.style;b.top=d.top;b.left=d.left;b.borderWidth=d.borderWidth;b.borderColor=d.borderColor;b.borderStyle=d.borderStyle;b.zIndex=d.zIndex;b.position=d.position;b.display=d.display;b.opacity=d.opacity;g=!1;a.removeChild(h);document.removeEventListener("keydown",c,!1);l&&
l.onclose&&(l.onclose(),l=null)}var d=null,g=!1;b=b||{};void 0==b.backgroundColor&&(b.backgroundColor="#333");void 0==b.zIndex&&(b.zIndex=999);void 0==b.opacity&&(b.opacity=.9);var h=document.createElement("img");h.width=25;h.height=25;h.src=hi5.tool.getImage("del","del.png");h.className="h5-img-btn";h.style.cursor="pointer";h.align="top";h.style.position="absolute";b.close?(h.style.top=b.close.top,h.style.right=b.close.right):(h.style.top=0,h.style.right=0);this.resize=e;var l=null;this.show=function(){var f=
a.style;l=this;d={position:f.position,top:f.top,left:f.left,borderWidth:f.borderWidth,borderColor:f.borderColor,display:f.display,zIndex:f.zIndex,borderStyle:f.borderStyle,opacity:f.opacity};f.position="absolute";f.display="block";f.borderStyle="solid";f.borderColor=b.backgroundColor;f.top=0;f.left=0;f.zIndex=b.zIndex;f.opacity=b.opacity;e();window.addEventListener("resize",e,!1);g=!0;a.appendChild(h);document.addEventListener("keydown",c,!1);if(this.onopen)this.onopen()};this.visible=function(){return g};
this.dismiss=f;h.addEventListener("click",f,!1)};
hi5.canvas={TextSelect:function(a,b,e,c,f){f||(f=a.canvas.width-1);b--;this.clear=function(){a.clearRect(0,0,a.canvas.width,a.canvas.height)};this.draw=function(d,g,h,l){var k=Math.min(d,h),m=Math.min(g,l);d=Math.abs(h-d)-1;h=Math.abs(l-g)-1;g=Math.abs(l-g)<1.5*b;a.strokeStyle=e||"#61D2D6";a.lineWidth=c||"1px";a.beginPath();g?a.rect(k,m,d,h):(a.moveTo(k,m),a.lineTo(f,m),2>f-k-d?(a.lineTo(f,m),a.lineTo(f,m+h)):(a.lineTo(f,m+h-b),a.lineTo(k+d,m+h-b),a.lineTo(k+d,m+h)),a.lineTo(0,m+h),a.lineTo(0,m+b),
a.lineTo(k,m+b),a.lineTo(k,m));a.stroke()}}};
hi5.DataTable=function(a){if(hi5.ui.initAs(a,"DataTable")){hi5.EventControl(a);"string"==typeof a&&(a=JSON.parse(a));var b=a.rows,e=a.cols;a.rowNo=-1;a.beforeGetValue=null;a.moveTo=function(b){a.rowNo=b};a.getColNo=function(a){for(var b=0,c=e.length;b<c;b++)if(e[b].name==a)return b;return-1};a.getValue=function(c){var e=b[a.rowNo][c];return a.beforeGetValue?a.beforeGetValue(c,e):e};a.setValue=function(c,e){a.beforeSetValue&&(e=a.beforeSetValue(c,e));b[a.rowNo][c]=e;a.fireEvent("onchange",[c,a.rowNo,
e])};a.first=function(){a.moveTo(0)};a.next=function(){a.moveTo(a.rowNo+1)};a.last=function(){a.moveTo(b.length-1)};a.hasNext=function(){return a.rowNo<b.length-1};a.remove=function(c){c||(c=a.rowNo);var e=[c];a.fireEvent("beforeremove",e);b.splice(c,1);a.fireEvent("onremove",e)};a.perform=function(b){"function"==typeof a[b]?a[b].apply(a):a.fireEvent("onaction",[b])};a.getObject=function(){for(var b={},f=0,d=e.length;f<d;f++)b[e[f].name]=a.getValue(f);return b};a.find=function(a,e){for(var c=0,f=
b.length;c<f;c++)if(b[c][a]==e)return b[c];return null}}a.fireEvent("onopen");return a};
hi5.DataGrid=function(a,b){function e(b){var d=this.rowIndex;"number"==typeof d&&(c=d-=a.tHead.rows.length,a.dataTable.moveTo(d));if(a.onrowclick)a.onrowclick(b)}if(!hi5.ui.initAs(a,"DataGrid"))return a;if("TABLE"!=a.nodeName)throw"Not HTML Table";a.dataTable=null;a.onrowclick=null;var c=-1;a.getValue=function(b){var d=a.dataTable;d.moveTo(c);return d.getValue(d.getColNo(b))};a.fillData=function(f){var d=f.rows,g=a.tBodies[0],h;a._rowTemp||(a._rowTemp=a.tBodies[0].rows[0].cloneNode(!0));var l=a._rowTemp;
var k=l.cells.length,m=g.cloneNode(!1);var p=d.length;for(h=0;h<p;h++){var q=l.cloneNode(!0);var n=q.cells;f.moveTo(h);for(d=0;d<k;d++)if(!n[d].innerHTML){var r=f.getValue(d);a.beforeDisplayValue&&(r=a.beforeDisplayValue(d,r));b?n[d].innerText=r:n[d].innerHTML=r}c=h;q.addEventListener("click",e,!1);a.beforeAppendRow&&a.beforeAppendRow(q);m.appendChild(q)}a.removeChild(g);a.appendChild(m)};a.open=function(){a.dataTable&&(a.fillData(a.dataTable),a.dataTable.addEvent("onremove",function(b){var c=a.tBodies[0];
(b=c.rows[b])&&c.removeChild(b)}))};a.clear=function(){if(a._rowTemp){a.removeChild(a.tBodies[0]);var b=document.createElement("tbody");b.appendChild(a._rowTemp);a.appendChild(b)}};return a};
hi5.Select=function(a,b,e){if(!hi5.ui.initAs(a,"Select"))return a;var c=a.parentNode,f=document.createElement("div");f.style.padding="0";f.style.display="inline";c.insertBefore(f,a);var d=document.createElement("img");d.src=hi5.tool.getImage("select","select.png");d.height=a.offsetHeight;d.style.verticalAlign="-6px";f.appendChild(a);f.appendChild(d);var g=document.createElement("select");b&&(g.multiple=!0,e||(e=","));c=a.getAttribute("hi5_size");g.size=c?c:10;if(c=a.getAttribute("hi5_list"))if(c=
c.split(";"),f=c.length,0<f)for(var h=g.options,l=0;l<f;l++)h[l]=new Option(c[l]);g.style.position="absolute";g.style.zIndex=99999;g.style.display="none";document.body.appendChild(g);a.show=function(){a.beforedropdown&&a.beforedropdown(a);g.style.display="";g.focus()};a.hide=function(){g.style.display="none";a.focus()};d.onclick=function(){if("none"==g.style.display){if(0==g.options.length){var b=a.getAttribute("onfetchlist");b&&eval(b)}b=hi5.tool.getPos(a,!1);g.style.left=b.x+"px";g.style.top=b.y+
a.offsetHeight+"px";g.style.width=a.offsetWidth+d.width+3+"px";a.show()}else a.hide()};g.onchange=function(){if(b){for(var c=[],d,f=g.options,h=0,l=f.length;h<l;h++)d=f[h],d.selected&&c.push(d.value);a.value=c.join(e)}else a.value=g.value,g.style.display="none";if(a.onchange)a.onchange()};a.options=g.options;return a};hi5.init.push(function(){for(var a=document.getElementsByClassName("Hi5Select"),b=a.length,e=0;e<b;e++)new hi5.Select(a[e])});
hi5.Tab=function(a){function b(b){var c=d;d!=b&&(g[d].className="tab_back",h[d].className="tab_hide",d=b);g[b].className="tab_front";h[b].className="tab_show";g[b].focus();c!=b&&a.fireEvent("ontabchange",[b,c])}function e(a){a=g.indexOf(a.target);-1!=a&&b(a)}if(!hi5.ui.initAs(a,"Tab"))return a;hi5.EventControl(a);for(var c=a.getElementsByClassName("tab")[0].getElementsByClassName("tab_title")[0].childNodes,f=c.length,d=0,g=[],h=[],l=0;l<f;l++){var k=c[l];"SPAN"==k.nodeName.toUpperCase()&&(k.className=
"tab_back",k.onclick=e,k.onfocus=e,g[g.length]=k)}c=a.getElementsByClassName("tab_body")[0].childNodes;f=c.length;for(l=0;l<f;l++)k=c[l],"DIV"==k.nodeName.toUpperCase()&&(h[h.length]=k,k.className="tab_hide");b(d);a.setSelected=b;a.getSelected=function(){return d};return a};hi5.init.push(function(){for(var a=document.getElementsByClassName("tab_all"),b=a.length,e=0;e<b;e++)new hi5.Tab(a[e])});
hi5.notifications=new function(){function a(a){var c=new b(a);e.getElement().appendChild(c);a.select&&(a=c.getElementsByClassName("hi5_notifer_msg")[0],"TEXTAREA"==a.nodeName?a.select():hi5.browser.selectEditable(a))}function b(b){function c(a,b){var c=document.createElement("span");c.className=b;c.onclick=function(b){a.apply(d,[b])};return c}var d=document.createElement("div");d.className="hi5_notifer slideUp";d.title=b.title;d.message=b.msg;d.msgCount=1;var g=document.createElement("div");g.className=
"hi5_notifer_title";var h=document.createElement("span");h.className="hi5_notifer_icon";g.appendChild(h);g.appendChild(document.createTextNode(d.title));d.appendChild(g);g=document.createElement("div");h="text/plain"==b.format?document.createElement("textarea"):document.createElement("div");h.className="hi5_notifer_msg";h.style.width="100%";h.innerHTML=b.msg;g.appendChild(h);if(!e.disableCounter){var l=document.createElement("span");l.className="hi5_notifer_count";d.addCount=function(a){d.msgCount+=
a||1;l.innerHTML="("+d.msgCount+")"};b.count&&1<b.count&&d.addCount(b.count-1);g.appendChild(l)}d.appendChild(g);b.cbNo&&d.appendChild(c(b.cbNo,"hi5_notifer_button_no"));b.cbYes&&d.appendChild(c(b.cbYes,"hi5_notifer_button_yes"));d.destroy=function(){if(d.parentNode){d.parentNode.removeChild(d);var c=e.notifyPool.shift();if(c)a(c);else if(e.onempty&&0==e.notifySize())e.onempty();b.cbClose&&b.cbClose()}};if(b.timeout){var k=setTimeout(function(){d.destroy()},b.timeout);d.addEventListener("mouseover",
function(){clearTimeout(k)},!1)}b.cbYes||b.cbNo||(d.onclick=d.destroy);return d}this.notifyPool=[];this.disableCounter=!1;this.getElement=function(){var a=hi5.$("hi5_notifer_all");a||(a=document.createElement("div"),a.id="hi5_notifer_all",document.body.appendChild(a));return a};var e=this;this.notify=function(b){b="string"==typeof b?{msg:b,title:"",count:1}:b;b.title||(b.title="");b.count||(b.count=1);if(!e.onnotify||!e.onnotify(b)){var c=hi5.tool.getChildNodesByTag(e.getElement(),"div"),d=c.length;
if(!e.disableCounter&&0<d&&(c=c[d-1],c.title==b.title&&c.message==b.msg)){c.addCount();return}if(3>d)a(b);else{d=e.notifyPool;if(!e.disableCounter&&0<d.length&&(c=d[d.length-1],c.title==b.title&&c.msg==b.msg)){c.count++;return}d.push(b)}}};this.notifySize=function(){return hi5.tool.getChildNodesByTag(e.getElement(),"div").length};this.clearAll=function(){e.notifyPool.length=0;for(var a=e.getElement();a.hasChildNodes();)a.removeChild(a.firstChild)}};
hi5.file={readAsArrayBuffer:function(a,b){var e=new FileReader;e.onloadend=function(a){b(new Uint8Array(a.target.result))};e.readAsArrayBuffer(a)},getEntries:function(a){var b=a.target&&(a.target.webkitEntries||a.target.entries||[]);if(!b.length&&(a=a.dataTransfer&&a.dataTransfer.items))for(var e=0,c;c=a[e];++e)if("file"==c.kind){if(!c.webkitGetAsEntry&&!c.getAsEntry)break;c=c.webkitGetAsEntry()||c.getAsEntry();if(!c)break;b.push(c)}return b},getFilesFromEntries:function(a,b){function e(){d--;d||
b(g)}function c(a){return function(b){b.fullPath=a;g.push(b);e()}}function f(a){var b=a.length;d+=b;for(var g=0;g<b;g++){var h=a[g];h.isFile?h.file(c(h.fullPath),function(a){console.log(a);e()}):h.isDirectory&&h.createReader().readEntries(function(a){a.length&&f(a);e()},function(){e()})}}var d=0,g=[];f(a)},DirectoryReader:function(a){function b(a,b){var c=a.createReader(),d=[],e=function(){c.readEntries(function(a){a.length?(d=d.concat(Array.prototype.slice.call(a||[],0)),e()):b(d)})};e()}function e(a){for(var d=
0,f=a.length;d<f;d++){var h=a[d];h.isFile?h.file(function(a){return function(b){c.onfile(b,a)}}(h.fullPath)):h.isDirectory&&b(h,function(a){e(a)})}}var c=this;this.start=function(){e(a)}}};
hi5.Chat=function(a,b){function e(a,b,c){var d=document.createElement("span");d.className=b;d.innerHTML=a;c.appendChild(d);return d}function c(){var a=d.value;h.add(a,b);d.value="";if(h.onchat)h.onchat(a,b)}var f=hi5.$("chatHistory"),d=hi5.$("chatText"),g=hi5.$("chatSend"),h=this;this.add=function(c,d){var g=document.createElement("div");e((d||b)+":","chatFrom",g);e(c,"chatMsg",g);var h=new Date;e(h.getHours()+":"+h.getMinutes()+":"+h.getSeconds(),"chatTime",g);"block"!=a.style.display&&(a.style.display=
"block");f.appendChild(g);f.scrollTop=f.scrollHeight};d.addEventListener("keydown",function(a){13==a.keyCode&&c()},!1);g.addEventListener("click",c,!1)};document.addEventListener("DOMContentLoaded",hi5.init.start,!1);
