var hi5=hi5||{};String.prototype.trim||(String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")});Number.prototype.toByte||(Number.prototype.toByte=function(){var a=this&255;return 127<a?a-256:a});Date.now||(Date.now=function(){return(new Date).getTime()});String.prototype.applyArgs||(String.prototype.applyArgs=function(a){for(var b=this.split("%"),d,c,f=b[0],e=1,h=b.length;e<h;e++){d=b[e];var g=parseInt(d,10);isNaN(g)?f+=d:(c=d.substring((g+"").length),(d=a[g-1])&&(f+=d),f+=c)}return f});
String.prototype.hashCode||(String.prototype.hashCode=function(){for(var a=0,b,d=this.length,c=0;c<d;c++)b=this.charCodeAt(c),a=(a<<5)-a+b|0;return a});String.prototype.startsWith||(String.prototype.startsWith=function(a,b){return this.substr(!b||0>b?0:+b,a.length)===a});String.prototype.trimRight||(String.prototype.trimRight=function(){for(var a=this.length-1,b=a;0<=b&&" "==this[b];)b--;return b==a?this:0<b?this.substr(0,b+1):""});
Array.prototype.removeElm||(Array.prototype.removeElm=function(a){a=this.indexOf(a);-1!=a&&this.splice(a,1)});Date.prototype.getStdTimezoneOffset||(Date.prototype.getStdTimezoneOffset=function(){var a=new Date(this.getFullYear(),0,1),b=new Date(this.getFullYear(),6,1);return Math.max(a.getTimezoneOffset(),b.getTimezoneOffset())});
hi5.DateUtils={formatNum:function(a){return 10>a?"0"+a:""+a},formatDate:function(a,b){if(!a)return"";var d=new Date(a),c=d.getFullYear()+"-"+hi5.DateUtils.formatNum(d.getMonth()+1)+"-"+hi5.DateUtils.formatNum(d.getDate());b&&(c+=0+d.getHours()+":"+d.getMinutes());return c},parseDate:function(a){var b=a.split(" ");a=b[0].split("-");return 3!=a.length?null:1<b.length?(b=b[1].split(":"),2!=b.length?null:new Date(a[0],a[1]-1,a[2],b[0],b[1])):new Date(a[0],a[1]-1,a[2])}};
hi5.NumUtils={toBytes:function(a,b){var d=a.toString(16),c=d.length/2,f=c|0,e=0;for(b||(b=new Uint8Array(8));e<f;e++)b[e]=parseInt(d.substr(2*-(e+1),2),16);c>f&&(b[e]=parseInt(d[0],16));return b},splitInt64:function(a){return{high:Math.floor(a/4294967296),low:(a&4294967295)>>>0}},joinInt32:function(a,b){return 4294967296*b+a},ruuid:{getNext:function(){var a=performance.now(),b=(Date.now()-151479E7+(a|0)).toString(16);console.log("b44:"+b);var a=((a%1*1E5&16383)<<6|63*Math.random()).toString(16),d=
5-a.length;for(console.log("b20:"+a);d--;)a="0"+a;b+=a;12==b.length&&console.log("...");return b},test:function(){var a=[],b;for(b=0;9>b;b++)a.push(this.getNext());for(b=0;8>b;b++)a[b]>=a[b+1]&&console.log("error "+b,a[b],a[b+1])}}};
hi5.Arrays={fill:function(a,b,d,c){if(a.fill)a.fill(c,b,d);else for(;b<d;b++)a[b]=c},arraycopy:function(a,b,d,c,f){if(d.set&&a.subarray)d.set(a.subarray(b,b+f),c);else for(var e=0;e<f;e++)d[c+e]=a[b+e]},equals:function(a,b){if(a==b)return!0;if(!a||!b)return!1;var d=a.length;if(d!=b.length)return!1;for(var c=0;c<d;c++)if(a[c]!=b[c])return!1;return!0},startWidth:function(a,b){for(var d=0,c=b.length;d<c;d++)if(a[d]!=b[d])return!1;return!0},__sortNumber:function(a,b){return a-b},sortNumber:function(a){return a.sort(hi5.Arrays.__sortNumber)},
hashCode:function(a){for(var b=1,d=0,c=a.length;d<c;d++)b=31*b+a[d]|0;return b},release:function(a){if(a)for(var b=0,d=a.length;b<d;b++)a[b]=null}};hi5.callback={callbacks:{},no:0,put:function(a){var b="CB"+this.no++;this.callbacks[b]=a;return b},get:function(a){var b=this.callbacks[a];b&&delete this.callbacks[a];return b}};
hi5.string={seperatedStr:{indexOf:function(a,b,d){var c=a.indexOf(b,0);var f=b.length,e=a.length;d=d||",";if(-1==c)return-1;if(0==c&&(f==a.length||a.charAt(f)==d))return 0;for(;a.charAt(c-1)!=d||a.charAt(c+f)!=d&&c+f!=e;)if(c+=1,c=a.indexOf(b,c),-1==c)return-1;return c}},queryToObj:function(a,b){a||(a=location.search.substring(1));var d=b||{};if(a)for(var c=a.split("&"),f=c.length,e=0;e<f;e++){var h=c[e].split("=");d[h[0]]=decodeURIComponent(h[1])}return d}};hi5.graphic={};
hi5.graphic.Line=function(a,b,d,c){this.x1=a||0;this.y1=b||0;this.x2=d||0;this.y2=c||0};hi5.graphic.Line.prototype.set=function(a,b,d,c){this.x1=a;this.y1=b;this.x2=d;this.y2=c};hi5.graphic.Line.prototype.intersection=function(a,b,d,c){var f=this.x1,e=this.y1,h=this.x2,g=this.y2,l=(c-b)*(h-f)-(d-a)*(g-e);if(0==l)return null;d=((d-a)*(e-b)-(c-b)*(f-a))/l;a=((h-f)*(e-b)-(g-e)*(f-a))/l;return 0<=d&&1>=d&&0<=a&&1>=a?{x:f+(d*(h-f)|0),y:e+(d*(g-e)|0)}:null};
hi5.graphic.Rectangle=function(a,b,d,c){this.x=a;this.y=b;this.width=d;this.height=c;var f=this;this.union=function(a,b,c,d){var g=f.width,e=f.height;if(0>(g|e))f.x=a,f.y=b,f.width=c,f.height=d;else if(!(0>(c|d))){var k=f.x,l=f.y,g=g+k,e=e+l;c+=a;d+=b;k>a&&(k=a);l>b&&(l=b);g<c&&(g=c);e<d&&(e=d);f.x=k;f.y=l;f.width=g-k;f.height=e-l}};this.intersection=function(a,b,c,d,m){var g=f.x,e=f.y;var l=g+f.width;var h=e+f.height;c=a+c;d=b+d;g<a&&(g=a);e<b&&(e=b);l>c&&(l=c);h>d&&(h=d);l-=g;h-=e;return m?(m.x=
g,m.y=e,m.width=l,m.height=h,m):new hi5.graphic.Rectangle(g,e,l,h)};this.isEmpty=function(){return 0>=f.width||0>=f.height}};
hi5.graphic.Bitmap=function(a,b,d){var c=32==d,f=d/8,e=(4-a*f%4)%4,h=c?108:40,g=14+h,l=(a*f+e)*b,m=g+l,n=new Uint8Array(m),k=new hi5.DataBuffer(n,0,m);k.setByte(66);k.setByte(77);k.setLittleEndian32(m);k.skipPosition(4);k.setLittleEndian32(g);k.setLittleEndian32(h);k.setLittleEndian32(a);k.setLittleEndian32(b);k.setLittleEndian16(1);k.setLittleEndian16(d);k.setLittleEndian32(c?3:0);k.setLittleEndian32(l);k.setLittleEndian32(2835);k.setLittleEndian32(2835);k.skipPosition(8);c&&(k.setLittleEndian32(16711680),
k.setLittleEndian32(65280),k.setLittleEndian32(255),k.setLittleEndian32(4278190080),k.setLittleEndian32(1466527264),k.skipPosition(36),k.skipPosition(12));this.getWidth=function(){return a};this.getHeight=function(){return b};this.getColor=function(){return d};this.getPaddingSize=function(){return e};this.putPixels=function(b,c,d){if(e)for(var g,l=a*f;c<d;)g=c+l,g>d&&(g=d),k.setBytes(b,c,g),c=g,k.skipPosition(e);else k.setBytes(b,c,d)};this.getDataURL=function(){return"data:image/bmp;base64,"+hi5.Base64.enc(k.getData())};
this.getData=function(){return k.getData()}};
hi5.Base64={table:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".split(""),enc:function(a,b,d){var c="",f=this.table;b||(b=a.length);d||(d=0);for(var e=d,h=d+b-2,g=b%3;e<h;e+=3)c+=f[a[e]>>2],c+=f[((a[e]&3)<<4)+(a[e+1]>>4)],c+=f[((a[e+1]&15)<<2)+(a[e+2]>>6)],c+=f[a[e+2]&63];2==g?(e=d+b-2,c+=f[a[e]>>2],c+=f[((a[e]&3)<<4)+(a[e+1]>>4)],c+=f[(a[e+1]&15)<<2],c+="="):1==g&&(e=d+b-1,c+=f[a[e]>>2],c+=f[(a[e]&3)<<4],c+="==");return c},binaries:[-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,62,-1,-1,-1,63,52,53,54,55,56,57,58,59,60,61,-1,-1,-1,0,-1,-1,-1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,-1,-1,-1,-1,-1,-1,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,-1,-1,-1,-1,-1],dec:function(a,b,d){var c=this.binaries,f=0,e=0;var h=a.indexOf("=")-b;var g=a.length;0>h&&(h=g-b);h=3*(h>>2)+Math.floor(h%4/1.5);d=d?new Uint8Array(h):Array(h);for(h=d[0]=
0;b<g;b++){var l=c[a.charCodeAt(b)&127];var m="="==a.charAt(b);-1==l?console.log("Illegal character '"+a.charCodeAt(b)+"'"):(e=e<<6|l,f+=6,8<=f&&(f-=8,m||(d[h++]=e>>f&255),e&=(1<<f)-1))}return d}};
hi5.DataBuffer=function(a,b,d){b||(b=0);d||(d=a.length);this.size=d;var c=b,f=b+d,e=hi5.Arrays.arraycopy,h=this;this.attach=function(b,d,e){a&&(a=null);a=b;c=d;h.size=e;f=d+e};this.reset=function(a){c=0;h.size=f=a};this.markEnd=function(a){f=a||h.getPosition()};this.getEnd=function(){return f};this.has=function(a){return f-c>=a};this.getByte=function(){return a[c++]};this.getBytes=function(b){if(a.slice)var d=a.slice(c,c+b);else if(a.buffer&&a.buffer.slice)d=new Uint8Array(a.buffer.slice(c,c+b));
else if(d=Uint8Array?new Uint8Array(b):Array(b),d.set&&a.subarray)d.set(a.subarray(c,c+b));else for(var g=0;g<b;g++)d[g]=a[c+g];c+=b;return d};this.getArrayBuffer=function(b){return a.buffer.slice(c,c+b)};this.cloneBytes=function(b){return new Uint8Array(a.buffer.slice(c,c+b))};this.copyToByteArray=function(b,c,d,f){e(a,d,b,c,f)};this.getCapacity=function(){return a.length};this.getPosition=function(){return c};this.getLittleEndian16=function(){var b=a[c+1]<<8|a[c];c+=2;return b};this.getBigEndian16=
function(){var b=a[c]<<8|a[c+1];c+=2;return b};this.getLittleEndian32=function(){var b=a[c+3]<<24|a[c+2]<<16|a[c+1]<<8|a[c];c+=4;return b};this.getLittleEndian64=function(){var b=a[c+7]<<56|a[c+6]<<48|a[c+5]<<40|a[c+4]<<32|a[c+3]<<24|a[c+2]<<16|a[c+1]<<8|a[c];c+=8;return b};this.getBigEndian32=function(){var b=a[c]<<24|a[c+1]<<16|a[c+2]<<8|a[c+3];c+=4;return b};this.getUnicodeString=function(a,b){for(var c=Math.floor(a/2),d="",e=0;e<c;e++){var f=this.getLittleEndian16();if(b&&0==f){this.skipPosition(2*
(c-e-1));break}d+=String.fromCharCode(f)}return d};this.getAscllString=function(b,d){var e="",g=b||f;if(a.subarray&&b&&!1===d)return e=c,c+=g,String.fromCharCode.apply(null,a.subarray(e,e+g));for(var l=0;l<g;l++){var h=this.getByte();if(0==h){b&&this.skipPosition(b-l-1);break}e+=String.fromCharCode(h)}return e};this.setAscllString=function(b){for(var d=0,e=b.length;d<e;d++)a[c++]=b.charCodeAt(d)};this.setUnicodeString=function(a){for(var b=a.length,c=0;c<b;c++)this.setLittleEndian16(a.charCodeAt(c))};
this.skipPosition=function(a){c+=a};this.setPosition=function(a){c=a};this.getData=function(){return a};this.setByte=function(b){a[c++]=b};this.setBytes=function(b,d,e){if(a.set){if(!d&&!e){a.set(b,c);c+=b.length;return}if(b.subarray){a.set(b.subarray(d,e),c);c+=e-d;return}}e||(e=b.length);for(d||(d=0);d<e;d++)a[c++]=b[d]};this.setLittleEndian16=function(b){a[c++]=b&255;a[c++]=b>>8&255};this.setLittleEndian32=function(b){a[c++]=b&255;a[c++]=b>>8&255;a[c++]=b>>16&255;a[c++]=b>>24&255}};
hi5.Logger=function(){var a=1;this.setLevel=function(b){a=b};this.debug=function(b){2<a&&console.log(b)};this.info=function(b){1<a&&console.log(b)};this.warn=function(b){0<a&&console.log(b)}};
hi5.httpGet=function(a,b){function d(a){b(!1,a.target.responseText)}function c(a){b(!0)}var f=b?!0:!1,e=new XMLHttpRequest;f&&(e.addEventListener("load",d),e.addEventListener("error",c),e.addEventListener("abort",c));e.open("GET",a,f);e.setRequestHeader("Content-Type","text/plain;charset=UTF-8");e.send(null);return f?"":e.responseText};var svGlobal={logger:new hi5.Logger,util:{}};
