var svGlobal=svGlobal||{logger:new hi5.Logger,util:{}};svGlobal.version="5.6.0";svGlobal.build="891";function cancelDefault(h){h.preventDefault&&h.preventDefault();h.stopPropagation&&h.stopPropagation();return!1}
function LocalInterface(h){function t(a){var b=a-hi5.browser.innerHeight;10<b&&22>b&&(a=hi5.browser.innerHeight);return a}function z(a){q.detectInput&&N&&W&&(sa||"text"==W.system||"none"==W.system?setTimeout(function(){Qa(!0)},5):setTimeout(function(){Qa(!1)},5));if(document.activeElement!=a||!f.focused){for(var b=a,d,c=[];b.parentElement;)if(b=b.parentElement,d=getComputedStyle(b))d.getPropertyValue("overflow"),"block"==d.getPropertyValue("display")&&c.push([b,b.scrollTop,b.scrollLeft]);a.focus();
if(c.length){a=0;for(d=c.length;a<d;a++){b=c[a];if(b[0].scrollTop!=b[1]||b[0].scrollLeft!=b[2])b[0].scrollTop=b[1],b[0].scrollLeft=b[2];c[a]=null}c=null}}}function C(){var a=[];this.sent=0;this.types=[];var b=this;this.datas=a;this.setData=function(d,c){if("text/plain"==d||"text/html"==d)2<c.length&&"`\t`"==c.substring(0,3)&&(c=c.substring(3)),c=c.replace(/\r?\n/g,"\r\n");b.types.push(d);a.push(c)};this.getData=function(d){var c=a[b.types.indexOf(d)];c||"text/richtext"!=d||(c=a[b.types.indexOf("text/html")]||
a[b.types.indexOf("text/plain")]);return c};this.removeData=function(d){d=b.types.indexOf(d);-1!=d&&(b.types.splice(d,1),a.splice(d,1))};this.equals=function(a){if(!a||!hi5.Arrays.equals(b.types,a.types))return!1;for(var c,d,l=b.types,v=0,e=l.length;v<e;v++)if(c=l[v],d=b.getData(c),c=a.getData(c),d!=c)return!1;return!0}}function I(a){function b(){return h?a.value:m.isFirefox?a.textContent:a.innerText}function d(){p&&(X="",p.setValue(""))}function c(a){O=a.keyCode;if(p.onkeydown)p.onkeydown(a)}function g(a){if(p.onkeyup)p.onkeyup(a);
a=a.keyCode;(13==a||32==a&&32==O)&&setTimeout(d,100)}function l(a){if(p.onbackspace)for(var c=0;c<a;c++)p.onbackspace()}function v(c){if(!p.disableTextInput){c.stopPropagation();c=b();var g=c.length;if(c!=X){var v=X.length,e=c.indexOf(X);if(c&&0===e){if(c=c.substring(v),0<c.length&&y&&p.ontextinput&&(p.ontextinput({data:c,target:a}),"."==c)){d();return}}else if(e=X.indexOf(c),0===e)8!=O&&l(v-g);else if(y&&(l(v),0<c.length&&p.ontextinput))p.ontextinput({data:c,target:a});""===b()&&setTimeout(d,100);
X=b()}}}function e(a){if(!p.disableTextInput&&a.data&&(a.stopPropagation(),Z&&a.preventDefault(),p.ontextinput))p.ontextinput(a)}function f(a){if(p.oncomposition)p.oncomposition(a)}this.unicode=!1;var p=this,y=m.isFirefox||m.isOpera||m.isAndroid&&m.isChrome,X="",O=0,h="INPUT"==a.nodeName||"TEXTAREA"==a.nodeName,k="DIV"==a.nodeName;this.setValue=function(c){var b=p.disableTextInput;p.disableTextInput=!0;h?a.value=c:k&&(a.innerHTML=c);p.disableTextInput=b};this.init=d;this.disableTextInput=!1;d();a.addEventListener("keydown",
c,!1);a.addEventListener("keyup",g,!1);a.addEventListener("keypress",function(a){if(p.onkeypress)p.onkeypress(a)},!1);y?(a.addEventListener("input",v,!1),a.addEventListener("mouseup",d,!1)):(a.addEventListener("textInput",e,!1),a.addEventListener("textinput",e,!1));a.addEventListener("compositionstart",f,!1);a.addEventListener("compositionend",f,!1);a.addEventListener("compositionupdate",f,!1);this.release=function(){p=null;a.removeEventListener("keydown",c,!1);a.removeEventListener("keyup",g,!1);
a.removeEventListener("input",v,!1);a.removeEventListener("focus",d,!1);a.removeEventListener("textInput",e,!1);a.removeEventListener("textinput",e,!1);a=null};this.select=function(){gb(a)}}function U(a,b,d){function c(a){var c=Ca(a);var d=a.deltaMode||0;var p=!!a.deltaX||!!a.wheelDeltaX;a.preventDefault();a.stopPropagation();if(1==d)b(-a.deltaY||-a.deltaX,c,p);else{var y="deltaY"in a?40:"wheelDelta"in a?120:0;if(y){d=Date.now();100<d-l&&(g=0);var v=-a.deltaY||-a.deltaX||a.wheelDelta;0!=v&&(g+=v,
a=g/y|0,g%=y,0!==a&&b(a,c,p));l=d}else a=-a.detail,32768==Math.abs(a)&&(v=window.innerHeight/40|0,a=0>a?-v:v),b(a,c,!1)}}var g=0,l=0;a.addEventListener("DOMMouseScroll",c,!0);a.addEventListener("mousewheel",c,!0)}function x(a){function b(a){if(!l&&v.onmousedown)v.onmousedown(a)}function d(a){if(!l&&v.onmousemove)v.onmousemove(a)}function c(a){if(f&&f.focused)if(l)l=!1;else if(v.onmouseup)v.onmouseup(a)}function g(a){"touchstart"==a.type&&(l=!0);if(v.ontouch)v.ontouch(a)}var l=!1,v=this,e=navigator.pointerEnabled||
navigator.msPointerEnabled||!1;"ontouchstart"in window||!e?(a.addEventListener("touchstart",g,!1),a.addEventListener("touchend",g,!1),a.addEventListener("touchmove",g,!1),a.addEventListener("touchcancel",g,!1),document.addEventListener("mousemove",d,!1),a.addEventListener("mousedown",b,!1),document.addEventListener("mouseup",c,!1)):navigator.pointerEnabled?(a.addEventListener("pointerdown",g,!1),a.addEventListener("pointerup",g,!1),a.addEventListener("pointermove",g,!1),a.addEventListener("pointercancel",
g,!1)):navigator.msPointerEnabled&&(a.addEventListener("MSPointerDown",g,!1),a.addEventListener("MSPointerUp",g,!1),a.addEventListener("MSPointerMove",g,!1),a.addEventListener("MSPointerCancel",g,!1))}function Y(){return ca?!0:!ga&&F<=window.innerWidth&&G<=window.innerHeight}function ta(a){function b(a,b){for(var d,g=a.length,p=Array(g),y=0;y<g;y++){d=a[y];var v=Da(d.clientX,d.clientY,h),O=y;d=d.identifier;if(!(256>d)){var l=c.indexOf(d);-1!=l?d=l:(c.push(d),d=c.length-1)}p[O]={contactId:d,contactFlags:b,
x:v.x,y:v.y}}return p}var d,c=[],g=!1;this.handle=function(l){var v=l.type,e=l.touches,f=l.changedTouches;cancelDefault(l);switch(v){case "touchstart":g=!1;d=l=b(e,25);break;case "touchmove":l=b(f,26);d||(d=b(e||f,25));e=!1;if(0<d.length&&1==l.length){a:{f=d.length;for(v=0;v<f;v++)if(d[v].contactId==l[0].contactId){f=v;break a}f=-1}-1!=f&&d[f].x==l[0].x&&d[f].y==l[0].y&&(e=!0)}if(e)break;else 0<d.length&&(a.redirectTouches(d),d.length=0);a.redirectTouches(l);g=!0;break;case "touchend":if(g)l=b(f,
4);else{a.redirectTouches(d);l=d.length;for(e=0;e<l;e++)d[e].contactFlags=4;l=d}a.redirectTouches(l);c.length=d.length=0;break;case "touchcancel":a.redirectTouches(b(f,34)),c.length=d.length=0}}}function hb(a){function b(a){var c=a[1].screenX-a[0].screenX;a=a[1].screenY-a[0].screenY;return Math.sqrt(c*c+a*a)}function d(a,d){var p=[],y=c(a,u[0].identifier)||c(d,u[0].identifier);y&&p.push(y);(y=c(a,u[1].identifier)||c(d,u[1].identifier))&&p.push(y);y="";if(2!=p.length)return y;var g=b(p)-b(u);60>Math.abs(g)?
80<p[0].screenX-u[0].screenX?y="RIGHT":80<u[0].screenX-p[0].screenX?y="LEFT":80<p[0].screenY-u[0].screenY?y="DOWN":80<u[0].screenY-p[0].screenY&&(y="UP"):y=0>g?"CLOSE":"OPEN";return y}function c(a,c){for(var b=0,p=a.length;b<p;b++)if(a[b].identifier==c)return a[b];return null}function g(a){this.identifier=a.pointerId;this.clientX=a.clientX;this.clientY=a.clientY;this.pageX=a.pageX;this.pageY=a.pageY;this.screenX=a.screenX;this.screenY=a.screenY}var e=0,v=0,f=0,k=0,p=!1,y=0,X=0,O=0,q=0,n=!1,r=!1,w=
3,t=!1;Z&&(w*=3);this.delay=!1;var u=[],m=this;this.handlePointer=function(a){if(a.pointerType==a.MSPOINTER_TYPE_MOUSE||"mouse"==a.pointerType)switch(a.type){case "MSPointerDown":case "pointerdown":Ra(a);break;case "pointermove":case "MSPointerMove":Sa(a);break;case "pointerup":case "MSPointerUp":Ta(a)}else a.touches=a.changedTouches=[new g(a)],m.handle(a)};this.handle=function(b){var g=b.type,l=b.touches;var T=b.changedTouches;var E=0,m=0;switch(g){case "touchstart":case "MSPointerDown":case "pointerdown":t=
!1;v="touchstart"==g?l.length:v+1;r=!1;k=Date.now();p=1==v&&200>k-f;g=l[0];e=g.identifier;m=Da(g.clientX,g.clientY,h);y=m.x|0;X=m.y|0;n=!0;2!=l.length?t=!1:(E=l[1].screenX-l[0].screenX,t=100<Math.abs(l[1].screenY-l[0].screenY)||350<Math.abs(E));(p||1<v&&!t)&&cancelDefault(b);if(3==v){g=m=E=0;T=9999;for(var x=0,Pb=l.length;x<Pb;x++)l[x].screenY>g&&(g=l[x].screenY,E=x),l[x].screenY<T&&(T=l[x].screenY,m=x);u=[{screenX:l[m].screenX,screenY:l[m].screenY,identifier:l[m].identifier},{screenX:l[E].screenX,
screenY:l[E].screenY,identifier:l[E].identifier}]}break;case "pointermove":case "MSPointerMove":if(1<v)break;case "touchmove":if(t)return;g=T[l.length-1];if(!g)break;if(g.identifier!=e&&(g=c(T,e),!g)){cancelDefault(b);return}m=Da(g.clientX,g.clientY,h);E=m.x|0;m=m.y|0;if(n){if(0===E-y&&0===m-X)return;if(Math.abs(E-y)<w&&Math.abs(m-X)<w){cancelDefault(b);return}n=!1;T=Date.now()-k;if((r=88>T)&&!Y()&&1==v){t=!0;return}a.touchstart({x:y,y:X,flick:r,pointes:v,screenX:g.screenX,screenY:g.screenY,moved:!0,
target:b.target})}cancelDefault(b);a.touchmove({x:E,y:m,flick:r,pointes:v,moved:!0,screenX:g.screenX,screenY:g.screenY,target:b.target});break;case "MSPointerUp":case "touchend":case "pointerup":if(t)return;if(3==T.length+l.length){a.touchend({x:E,y:m,flick:r,pointes:v,moved:!n,target:b.target,gesture:d(l,T)});v=0;break}else{if(2<v){v=0;break}if(g=c(T,e))l=Date.now(),m=Da(g.clientX,g.clientY,h),E=m.x|0,m=m.y|0,r?a.touchend({x:E,y:m,flick:!0,pointes:v,moved:!n,screenX:g.screenX,screenY:g.screenY,target:b.target}):
(T=l-k,n?(f=l,p?cancelDefault(b):(O=E,q=m),500>T?(f=l,a.touchstart({x:O,y:q,flick:!1,pointes:v,screenX:g.screenX,screenY:g.screenY,moved:!1,target:b.target}),a.touchend({x:O,y:q,flick:!1,pointes:v,moved:!1,screenX:g.screenX,screenY:g.screenY,target:b.target})):a.longpress({x:E,y:m,flick:!1,pointes:v,moved:!1,screenX:g.screenX,screenY:g.screenY,target:b.target})):a.touchend({x:E,y:m,flick:!1,pointes:v,moved:!0,screenX:g.screenX,screenY:g.screenY,target:b.target}))}v=0;break;case "MSPointerCancel":case "touchcancel":v=
0}p&&cancelDefault(b)}}function Qb(){r(!0,14);r(!1,14)}function gb(a){try{a.select?a.select():m.selectEditable(a)}catch(b){svGlobal.logger.info(b)}}function ib(){function a(){g.focus()}function b(c,b){var p=document.createElement("a");p.href="#";p.accessKey=c;p.onfocus=a;p.style.position="absolute";p.style.width=1;p.style.height=1;p.style.left=0;p.style.top=b+"px";p.style.pointerEvents="none";return p}var d=f.forceTextArea||Z,c=document.createElement(d?"textarea":"div"),g=this;this.element=c;this.setFontSize=
function(a){c.style.fontSize=q.inputFontSize||a};d?(c.style.opacity=0,c.readOnly=N&&m.isMetro?!0:!1):c.contentEditable=!N||(m.isChrome||m.isFirefox)&&(m.isWindows||m.isCrOS)?!0:!1;c.setAttribute("autocomplete",m.isChrome?"new-password":"off");c.setAttribute("autocorrect","off");c.setAttribute("autocapitalize","off");c.setAttribute("spellcheck","false");c.accessKey="f";c.id="wsinput";c.tabIndex=1;c.style.opacity=0;c.style.resize="none";c.style.position="absolute";c.style.margin="0";c.style.border=
"none";c.style.outline="none";var l=hi5.tool.getPos(h,!0);c.style.left=l.x+"px";c.style.top=l.y+"px";c.style.paddingRight=0;c.style.paddingBottom=0;c.style.width="10px";c.style.height="10px";c.style.zIndex=88;c.style.cursor="default";c.style.fontWeight="normal";c.style.fonStyle="normal";c.style.overflow="hidden";N&&(c.style.fontSize="2em");m.isiOS?(c.addEventListener("focus",function(a){setTimeout(function(){a.target.style.fontSize="0px"},333)},!1),c.addEventListener("blur",function(a){a.target.style.fontSize=
"1em"},!1)):m.isFirefox?c.style.fontSize=0:d?c.style.fontSize="1px":m.isChrome||(c.style.textIndent="-999em");D=new I(c);D.onbackspace=Qb;l=h.parentNode;l.appendChild(c);m.isIE&&(l.appendChild(b("E"),60),l.appendChild(b("V"),61),l.appendChild(b("A"),62),l.appendChild(b("T"),63),l.appendChild(b("H"),64));var e=c.style.opacity,k=c.style.textIndent||0;this.resetCSS=function(){_fontSize=c.style.fontSize;e=c.style.opacity;c.style.opacity=0;c.style.textIndent=0};this.restoreCSS=function(){c.style.opacity=
e;c.style.textIndent=k};this.getValue=function(){return d?c.value:c.innerHTML};this.setValue=function(a){D&&(D.disableTextInput=!0);d?c.value=a:c.innerHTML=a;D&&(D.disableTextInput=!1)};this.focus=function(){g.setValue(" ");z(c)};this.setContentEditable=function(a){d?(a="true"==a,c.readOnly==a&&(c.readOnly=!a)):c.setAttribute("contenteditable",a)};this.isIMEMode=!1;this.setIMEStatus=function(a){a?g.isIMEMode||(d&&(c.style.background="transparent",c.style.opacity=1),g.isIMEMode=!0):g.isIMEMode&&(d&&
(c.style.background="",c.style.opacity=0),g.isIMEMode=!1)};this.adjust=function(a){var b=hi5.tool.getPos(h,!0);w.offX=b.x;w.offY=b.y;var d=f.railWin?Math.min(window.innerWidth-b.x,F):F,g=f.railWin?Math.min(window.innerHeight-b.y,G):G;if(N){var l=Math.max(window.pageXOffset+100,b.x);a=Math.max(window.pageYOffset+100,b.y)}else{var e=Math.min(window.innerHeight-b.y,G);l=Math.round(.7*Math.min(window.innerWidth-b.x,F));a=Math.round(e*(a?.99:.7))}d-=l;g-=a;q.disableAdjust&&(a=l=0,d=h.offsetWidth,g=h.offsetHeight);
c.style.width=d+"px";c.style.height=g+"px";c.style.paddingLeft=l+"px";c.style.paddingTop=a+"px";c.style.left=b.x+"px";c.style.top=b.y+"px"};this.remove=function(){D&&(D.release(),D=null);c.parentNode&&c.parentNode.removeChild(c);c=null};this.hide=function(){c.style.visibility="hidden"};this.getElement=function(){return c};this.select=function(){gb(c)}}function ua(a){function b(){q.text||(q.text={});return q.text}function d(a){a=(a&16777215).toString(16).toUpperCase();return"00000".substring(0,6-a.length)+
a}function c(a,c,g,l,e){if(v){var p=b();a.fillStyle=p.backgroundFillStyle||"white";a.fillRect(c,g-e+2,l,e);a.fillStyle=p.fillStyle||"#337788";a.textBaseline="bottom";a.fillText(v,c+3,g-2);a.strokeStyle="#"+d(v.hashCode());a.lineWidth=2;a.beginPath();a.moveTo(c,g);e=.382*l|0;a.lineTo(c+e,g);a.stroke();a.strokeStyle="#"+d(f);a.beginPath();a.moveTo(c+e+1,g);a.lineTo(c+l,g);a.stroke()}}function g(){var a=e.getContext("2d"),d=a.getImageData(0,0,e.cursorWidth,e.cursorHeight);if(v){a.font=b().font||"11px Arial";
var g=1.2*(a.measureText("W").width+1)+4;e.width=Math.max(e.cursorWidth,a.measureText(v).width+4);e.height=e.cursorHeight+g;c(a,0,e.height-1,e.width,g)}else e.width=e.cursorWidth,e.height=e.cursorHeight;a.putImageData(d,0,0)}if(!e){var l=h.parentNode,v="",f=0;e=l.querySelector('canvas[name="svImgCursor"]');if(!e){e=document.createElement("canvas");e.setAttribute("name","svImgCursor");e.style.position="absolute";e.style.left=90;e.style.top=90;e.scrX=0;e.scrY=0;e.hotX=0;e.hotY=0;e.width=e.height=32;
e.__left=0;e.__top=0;e.__visible=!1;e.style.visibility="hidden";e.style.zIndex=87;var k=null;q.disableClickEffect||(k=document.createElement("div"),k.className="mouse-click-off",k.style.zIndex=89);e.setCursor=function(d){var p=d.width,g=d.height,l=d.rawData,f=0,h=0,k=e.getContext("2d");v&&(k.font=b().font||"11px Arial",f=k.measureText(v).width,h=1.2*(k.measureText("W").width+1)+4);if(a)if(v){if(a){e.cursorWidth=f;e.cursorHeight=h;e.hotX=d.hotX;e.hotY=-g;e.width=f;e.height=h+4;c(k,0,e.height-1,e.width,
h);return}}else e.__setVisible(!1);if(l&&p&&g){var E=p*g,m=0,q=k.createImageData(p,g),n=q.data,r=d.hotX-e.hotX,u=d.hotY-e.hotY;e.cursorWidth=p;e.cursorHeight=g;e.hotX=d.hotX;e.hotY=d.hotY;e.width=Math.max(p,f+4);e.height=g+h+4;v&&c(k,0,e.height-1,e.width,h);for(f=0;f<E;f++)d=l[f],n[m++]=d&255,n[m++]=d>>8&255,n[m++]=d>>16&255,n[m++]=d>>24&255;k.putImageData(q,0,0,0,0,p,g);e.__left-=r;e.__top-=u;e.style.left=e.__left+"px";e.style.top=e.__top+"px"}};e.__setVisible=function(a){e.__visible=a;e.style.visibility=
a?"visible":"hidden"};W&&W.rawData?e.setCursor(W):e.setCursor({rawData:[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-1,-1,-1,
-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-1,-16777216,-16777216,-16777216,-16777216,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-16777216,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-16777216,0,0,-16777216,-1,-1,-16777216,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-16777216,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,0,0,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,
-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],width:32,height:32,hotX:10,hotY:10});e.moveCursor=function(a,c,b,d,l){var p=a-e.hotX,y=c-e.hotY;e.__left=p;e.__top=y;e.style.left=p+"px";e.style.top=y+"px";if(v!=b||f!=d)v=b,f=d,g();k&&l&32768&&(k.style.left=a-30+"px",k.style.top=c-30+"px",k.className="mouse-click-on",setTimeout(function(){k.className="mouse-click-off"},500))};l.appendChild(e);k&&l.appendChild(k)}}}function Ua(a){if(!1!==q.disableScrollbars){var b=
document.body;a?(Va=a,b.style.overflow=a):(Va=F<=window.innerWidth&&G<=window.innerHeight?"hidden":"visible",b.style.overflow=Va)}}function va(a){var b=h.parentNode,d=window.innerWidth,c=window.innerHeight;Math.max(F,G)<Math.max(d,c)&&Math.min(F,G)<Math.min(d,c)?1!=K&&(hi5.tool.scale(b,1),K=V=1):(document.body.style.overflow="hidden",K=V=a?Math.min(window.innerWidth/F,window.innerHeight/G):1,hi5.tool.scale(b,K,K))}function Wa(){if(f.toolbar)f.toolbar.removeButton("svCloud");else{var a=hi5.$("svCloud");
a&&a.parentNode.removeChild(a)}}function jb(){var a=chrome.app.window.current();a&&a.fullscreen()}function Rb(){wa=null;if(document){var a=k.element;document.removeEventListener("mousemove",Sa,!1);a.removeEventListener("mousedown",Ra,!1);document.removeEventListener("mouseup",Ta,!1);a.removeEventListener("mouseleave",Ea,!1);a.removeEventListener("mouseenter",Ea,!1);a.removeEventListener("paste",u.onPaste,!1);a.removeEventListener("copy",u.onCopy,!1);a.removeEventListener("cut",u.onCopy,!1);a.removeEventListener("focus",
kb,!1);a.removeEventListener("blur",lb,!1);u&&(document.removeEventListener("paste",u.onPaste,!1),document.removeEventListener("copy",u.onCopy,!1),document.removeEventListener("cut",u.onCopy,!1))}if(window){window.removeEventListener("resize",mb,!1);window.removeEventListener("beforeunload",nb,!1);window.removeEventListener("unload",Fa,!1);W=null;e&&(e.parentNode&&e.parentNode.removeChild(e),e=null);f&&f.toolbar&&(f.toolbar.setFadable=null,f.toolbar.startFade=null,f.toolbar.style.display="none",hi5.ui.clean(f.toolbar),
f.toolbar=null);try{xa&&xa.parentNode&&(xa.parentNode.removeChild(xa),xa=null),k&&(k.remove(),k=null)}catch(b){}}}function Xa(a,b){var d=document.getElementById("_tmpEditable");a||(a="div");var c=document.body;d&&d.nodeName!=a.toUpperCase()&&(c.removeChild(d),d=null);d||(d=document.createElement(a),d.id="_tmpEditable","div"==a&&!1!==b&&(d.contentEditable=!0,Z&&(d.style.textIndent="-999px")),d.style.position="absolute",d.style.zIndex=9999,d.style.left=c.scrollLeft+50+"px",d.style.top=c.scrollTop+50+
"px",d.style.width="4px",d.style.height="4px",d.tabIndex=2,d.style.outline="none",d.style.opacity=0,d.style.overflow="hidden",c.appendChild(d));return d}function kb(a){f.focused||(Ya.clearPDF(),f.focused=!0,n.onfocus(a),f.focusTime=Date.now(),aa&&(S=n.fromSyncedSurface?n.fromSyncedSurface(200):!1,S||(u&&(u.clipData=null),n.send("891"+(f.onreqpaste||ob?1:0)))),n&&(n.checkLockFlags=!0),A.noKeyStuck||A.sendMissKey(),A.ctrlDelayed&&(A.ctrlDelayed=!1))}function nb(a){var b=__svi18n.remoteApp.close;if(!pb&&
f.railWin&&f.railWin.isRunning()&&b&&(a||(a=window.event),2!=n.getAppMode()))return f.showMessage(b),a&&(a.returnValue=b),b}function Fa(a){if(f&&(f.focused=!1,f.onunload))f.onunload()}function qb(){k&&(k.element.oncontextmenu=function(){return!1},Z||(k.element.onselectstart=function(){return!1}))}function mb(a){k&&k.adjust();if(ma)va(!0);else if(!(ga&&2500>Date.now()-ga)){var b=m.isWindows&&!m.isMetro;if(!N||b&&!ga||m.isCrOS||m.isChromeApp)n.onresize(a)}}function lb(a){f&&(f.focused=!1,f.blurTime=
Date.now())}function Sb(){window.svSurface||(window.svSurface=f);window.addEventListener("resize",mb,!1);if(!ha){var a=!m.isChromeApp;a&&window.addEventListener("beforeunload",nb,!1);a?window.addEventListener("unload",Fa,!1):chrome.runtime.onSuspend.addListener(Fa);qb();k.element.addEventListener("focus",kb,!1);k.element.addEventListener("blur",lb,!1);m.isChromeApp&&!q.disableMaxFullScn&&chrome.app.window.current().onMaximized.addListener(jb);(a=hi5.$("saveSession"))&&a.addEventListener("change",
function(a){n.saveSession({save:a.target.checked})})}}function rb(){if(!da){var a=hi5.$("touchGesture");a&&(a.style.display="block");if(a=hi5.$("extKBD"))a.onchange=function(a){f.setExtKeyboard(a.target.checked)};da=hi5.$("svTouchInput");try{window.parent==window||da||(da=window.parent.document.getElementById("svTouchInput"))}catch(b){}da&&"IMG"!=da.nodeName&&(a=document.createElement("img"),a.id="svTouchInput",a.src=q.img&&q.img.kbd||"kbd.png",da.parentNode.replaceChild(a,da),da=a)}}function na(a,
b){function d(a,c){var d=document.createElement("span");d.data_path=a;d.className="path";d.innerHTML=c;d.onclick=function(){na(this.data_path,b)};return d}function c(a){for(var c=g;c.hasChildNodes();)c.removeChild(c.firstChild);var b=d("/","&nbsp&nbsp&nbsp/");c.appendChild(b);if("/"!=a&&""!==a){a=a.split("/");for(var p="/",y=0,l=a.length;y<l;y++)b=a[y],""!==b&&(p=p+a[y]+"/",b=d(p,b+"/"),c.appendChild(b))}}var g=hi5.$("parentPath");g.currentDir||(g.currentDir="/");"."==a?a=g.currentDir:g.currentDir=
a;g.currentDir=a;b.visible()?hi5.tool.disableInput(hi5.$("filecontainer")):b.onopen=function(){hi5.tool.disableInput(hi5.$("filecontainer"))};var l=new hi5.DataGrid(hi5.$("filelist"));l.clear();n.getShareFiles(a,function(a){function d(c){c||(c=l.getValue("Name"));var b=a.parent;if(""===b||"/"!=b.charAt(b.length-1))b+="/";return b+c}a.error&&__svi18n.file[a.error]&&f.showMessage(__svi18n.file[a.error]);var g=new hi5.DataTable(a);l.dataTable=g;var p=hi5.tool.bytesToSize;l.beforeDisplayValue=function(a,
c){var b=g.cols[a].name;return"Date Modified"==b?(new Date(c)).toLocaleString():"Size"==b?p(c):"Type"==b&&"folder"==c?__svi18n.file.folder:"Name"==b?decodeURIComponent(c):c};l.onrowclick=function(c){var p=l.getValue("Name"),g=l.getValue("Type"),y=d(p);c=c.target.name;"delete"==c?(H.removeFile(y),na(a.parent,b)):"folder"==g?na(("/"==a.parent?"":a.parent)+"/"+p,b):("view"==c&&(y+="&action=view"),c&&n.getFile(y))};l.beforeAppendRow=function(a){var c;if("folder"==g.getValue(g.getColNo("Type"))){if(c=
a.querySelector('img[name="download"]'))c.style.visibility="hidden"}else{c=l.getValue("Name");var b=d(c),b="application/octet-stream:"+c+":"+n.getFileLink(b);a.addEventListener("dragstart",function(a){a.dataTransfer.setData("DownloadURL",b)},!1);if(10<c.length&&".uploading"==c.substring(c.length-10)){if(c=a.querySelector('img[name="download"]'))c.style.visibility="hidden";if(c=a.querySelector('img[name="view"]'))c.style.visibility="hidden"}}};l.open();c(a.parent);var y=document.getElementById("__diskSpace");
y&&(y.innerHTML=hi5.tool.bytesToSize(a.freeSpace)+"/"+hi5.tool.bytesToSize(a.totalSpace));b.resize();b.__position="\\\\tsclient\\"+a.name+a.parent.replace(RegExp("/","g"),"\\");hi5.tool.enableInput()})}function sb(a){H&&(a&&cancelDefault(a),a=hi5.$("filecontainer"),P=new hi5.ui.Lightbox(a),na(".",P),P.show(),P.onclose=function(){hi5.tool.enableInput()},(a=document.getElementById("__sv_folder__"))&&H.mkdirs&&(a.onclick=function(){var a=document.getElementById("__sv_folder_name_");a&&a.value&&(H.mkdirs(a.value),
na(".",P),a.value="")}),a=document.getElementById("__sv_position__"))&&(a.onclick=function(){n.writeKeyComb("Windows+R",20,function(){setTimeout(function(){n.writeText(P.__position,10,function(){r(!0,28);r(!1,28)})},666)});P.dismiss()})}function tb(){var a=hi5.$("svToolbar");if(a){for(var b=a.childNodes,d=!1,c=0,g=b.length;c<g;c++)if(1==b[c].nodeType&&-1==["svTouchInput","svCloud","svInfo"].indexOf(b[c].id)){d=!0;break}if(b=hi5.$("appinfo"))b.className="h5-form";if(f.showToolbar||N||H||b||d){a.style.left=
.45*window.innerWidth+"px";if(d=null===f.toolbar)f.toolbar=new hi5.Toolbar(a,q.toolbar.draggable,q.img.handle||"handle.png");N||(a=hi5.$("svTouchInput"))&&a.parentNode.removeChild(a);if(a=f.toolbar.getButton("svCloud"))H?(a.style.display="",a.onclick=sb):a.style.display="none";new hi5.Fadable(f.toolbar,q.toolbar.fadeDelay||5E3,k.element,"inline-block");a=q.toolbar.fadable;f.toolbar.setFadable(a);a&&(f.toolbar.style.display="none");if(a=f.toolbar.getButton("svInfo"))b?(a.style.display="",d&&(a.onclick=
function(a){cancelDefault(a);f.showConnectonInfo()})):a.style.display="none";if(f.onloadtoolbar)f.onloadtoolbar(f.toolbar)}}}function ub(a){H.addFiles(a.target.files,!1);a=hi5.$("uploadfile");var b=a.cloneNode(!0);a.parentNode.replaceChild(b,a);b.addEventListener("change",ub,!1)}function Tb(){var a=k.element;ea&&ea.release();ea=new svGlobal.util.MapDisk(a,H,!0);hi5.$("filecontainer")&&(Ga=new svGlobal.util.MapDisk(hi5.$("filecontainer"),H,!1),hi5.$("uploadfile").addEventListener("change",ub,!1))}
function Ea(a){e&&e.__setVisible(!1)}function vb(a){var b;if(B){if(a-Za>wb)if(w.isMultiMon){if(b=ya(w.left,w.top,w.right,w.bottom))B.putImageData(b.imgData,b.left-w.left,b.top-w.top,0,0,b.width,b.height),Za=a}else if(b=ya(0,0,w.right,w.bottom))B.putImageData(b.imgData,b.left,b.top,0,0,b.width,b.height),Za=a;Ha=requestAnimationFrame(vb)}}function xb(a,b,d,c){e||ua(q.cursorNameOnly);e.__visible||e.__setVisible(!0);a=e.scrX+a;b=e.scrY+b;0>a?a=0:a>F&&(a=F-1);0>b?b=0:b>G&&(b=G-1);e.scrX=a;e.scrY=b;var g=
a-e.hotX,l=b-e.hotY;Z&&(g=g/K|0,l=l/V|0);e.style.left=g+w.offX+"px";e.style.top=l+w.offY+"px";J&&!d&&n.sendInput("82"+a+"\t"+b);w.x=a;w.y=b;c&&(d=e.getBoundingClientRect(),3>d.top?window.scrollBy(0,-20):3>d.left?window.scrollBy(-20,0):d.bottom>window.innerHeight?window.scrollBy(0,20):d.right>window.innerWidth&&window.scrollBy(20,0))}function oa(a,b,d){a=a/K|0;b=b/V|0;f.moveCursor(a,b,d)}function Qa(a){k?k.setContentEditable(a?"true":"false"):document.getElementById("wsinput")&&input.setAttribute("contenteditable",
a?"true":"false");ga=a?1:0;Q&&Q.setVisibility(a);if(f.toolbar){var b=f.toolbar.getButton("svTouchInput");b&&(b.className=a?"h5-img-btn-on":"h5-img-btn")}}function $a(){(sa=!sa)&&k&&k.adjust();Qa(sa);k&&(k.element.blur(),k.element.focus())}function ab(a,b,d,c){switch(a){case "touchstart":bb=!1;0===e.scrX&&0===e.scrY&&oa(b-50,d-50);c&&(f.beforemousedown&&f.beforemousedown(e.scrX,e.scrY,0),n.sendInput("80"+e.scrX+"\t"+e.scrY+"\t0"));break;case "touchmove":c=b-Ia;a=d-pa;if(0===c&&0===a)return;var g=5>
Math.abs(yb)&&5>Math.abs(zb)&&(7<Math.abs(c)||7<Math.abs(a));g||(xb(c,a,!1,!0),bb=!0);yb=c;zb=a;break;case "touchend":if(a=!bb&&!c)f.beforemousedown&&f.beforemousedown(e.scrX,e.scrY,0),n.sendInput("80"+e.scrX+"\t"+e.scrY+"\t0");if(a||c)n.sendInput("81"+e.scrX+"\t"+e.scrY+"\t0"),f.aftermouseup&&f.aftermouseup(e.scrX,e.scrY,0)}Ia=b;pa=d}function Ub(a){J&&ja&&(a.touches||a.changedTouches?ja.handle(a):ja.handlePointer(a))}function Vb(a){if(!J)return!1;a.stopPropagation();A.check(a);var b=L.getKeyCode(a),
d="keydown"==a.type;d&&k&&k.setIMEStatus(229==b);if(Ab(a,b,d))return cancelDefault(a);17!=b||d||(ka=!1,Ja&&A.preKey.down&&ba(!1,A.preKey.code,L.getScancodeByKeyCode(A.preKey.code)));var c=L.getScancode(a);if(!L.isPrintableScancode(c,a)){A.afterComposition&&d&&(A.afterComposition=!1);if(A.onComposition||A.afterComposition&&!d)return!0;A["continue"](d,c,!0)&&r(d,c);return 17==b||(R||a.metaKey)&&(86==b||67==b||88==b)?(d&&(17==b&&Ka&&k&&la&&(a.target==k.element?(k.setValue("Copying... Please try again"),
k.select()):(M.setValue("Copying... Please try again"),M.select())),67==b||88==b)&&(ka=!0),17!=b||d||(ka=!1),!0):cancelDefault(a)}var g=A.isAltGr(d);g&&(ia=R=!1);g=!g&&(a.ctrlKey||a.altKey||a.metaKey);if(a.altKey&&g&&70<c&&83>c&&74!=c&&78!=c){if(56==A.preScancode.code||184==A.preScancode.code)r(!0,1),r(!1,1);g=!1}if(g)return(86!=b||!a.ctrlKey&&!a.metaKey||a.ctrlKey&&a.altKey||!aa)&&ba(d,b,L.getScancode(a)),d&&(La=b),17==b||(a.ctrlKey||a.metaKey)&&(86==b||67==b||88==b)?(!d||67!=b&&88!=b||(ka=!0),!0):
a.altKey&&!a.ctrlKey||a.ctrlKey&&!a.altKey||a.metaKey?cancelDefault(a):!0;if(!(b!=La||d||a.ctrlKey&&a.altKey))return ba(!1,b,L.getScancode(a)),La=0,cancelDefault(a);La=0;return!0}function Wb(a){A.onComposition="compositionend"!=a.type;A.afterComposition=!A.onComposition}function Ab(a,b,d){switch(b){case 8:case 35:if(!R&&!a.metaKey||!a.altKey||q.disableShortcuts||3==a.location)return!1;r(d,211);break;case 33:if(!a.altKey||q.disableShortcuts||3==a.location)return!1;r(d,15);break;case 34:if(!a.altKey||
q.disableShortcuts||3==a.location)return!1;d?(r(!0,42),r(!0,15)):(r(!1,15),r(!1,42));break;case 45:if(!a.altKey||q.disableShortcuts)return!1;r(d,1);break;case 36:if(!a.altKey||q.disableShortcuts||3==a.location)return!1;d?(r(!1,56),r(!0,29),r(!0,1)):(r(!1,1),r(!1,29));break;default:return!1}return!0}function Xb(a){if(!J)return!1;A.check(a);var b=L.getKeyCode(a),d="keydown"==a.type;d?k&&k.setIMEStatus(229==b):k&&k.isIMEMode&&Z&&k&&k.setIMEStatus(!1);var c=L.getScancode(a);if(Ab(a,b,d))return cancelDefault(a);
if(44==b){R||a.shiftKey?(r(!0,183),r(!1,183)):(r(!0,170),r(!0,183),r(!1,183),r(!1,170));var g=!0}else g=!1;if(g)return cancelDefault(a);g=86==b&&(Bb&&!d||(a.ctrlKey||a.metaKey)&&!(a.ctrlKey&&a.altKey))&&aa;0<c&&(g?Ma&&d&&Ma.sendCtrlVLater():A["continue"](d,c,!1)&&r(d,c));17!=b&&(Bb=g);return 17==b||(R||a.metaKey)&&(86==b||67==b||88==b)?(d&&(17==b&&Ka&&k&&la&&(k.setValue("Copying... Please try again"),k.select()),67==b||88==b)&&(ka=!0),17!=b||d||(ka=!1),!0):144==b||16==b?!1:cancelDefault(a)}function Yb(a){if(J&&
(a=a.data,"`\t`"!=a)){var b=R||ia;b&&(a=a.toLowerCase());a=a.replace(/\u00a0/g," ");if(f.onunicode){var d=f.onunicode(a);d&&(b=d.ctrl||d.alt)}n.sendInput("86"+a+"\t"+(b||Cb?1:0));Q&&Q.resetModifier()}}function Db(a,b){var d=a?a.getData(b):null;!d&&a&&(d=a.getData(a.types[0]));if(d&&"text/plain"==b){for(var c=0,g="",l=d.length;c<l&&(g=d.charAt(c),"\r"==g||"\n"==g);c++);c&&(d=d.substring(c))}if(d)return n.send("881"+b+"\t"+d),a.sent=Date.now(),!0;if(f.onreqpaste)return f.onreqpaste(b,function(a){n.send("881"+
b+"\t"+a)},function(){n.send("881ERROR\t")}),!0;n.send("881"+b+"\t");return!1}function Na(){n.writeKeyComb("ctrl+v",20)}function Zb(a){var b=0===a.types.length||a.equals(u.clipData),d=b?"":a.types.join(","),c=!0;if(!b){-1!=d.indexOf("text/html")&&-1==d.indexOf("text/richtext")&&(d+=",text/richtext");var g=a.getData("text/plain"),g=g?g.hashCode():0;n.send("880"+d+"\t"+g);u.clipData=a}f.onclipdata&&(c=!f.onclipdata(a,b));c&&setTimeout(Na,500)}function qa(a,b){if(58!=b||!D.unicode){if(f.onscancode){var d=
f.onscancode(a,b);if(d){for(var c=0,g=d.length;c<g;c++)n.sendInput("84"+(d[c].down?0:49152)+"\t"+d[c].key);return}}n.sendInput("84"+(a?0:49152)+"\t"+b);A.preScancode.code=b;A.preScancode.down=a}}function r(a,b){if(J){switch(b){case 221:if(a&&!q.disableKbdSync){qa(!0,221);qa(!1,221);return}break;case 58:if(a){if(Ja&&!q.disableKbdSync){qa(!0,58);qa(!1,58);return}n.localLockFlags^=4}break;case 69:a&&(n.localLockFlags^=2);break;case 70:a&&(n.localLockFlags^=1)}!A.isKeyDownSent(a,b)&&999<Date.now()-f.focusTime&&
qa(!0,b);qa(a,b)}}function ba(a,b,d){if(J){var c="8B"+(a?0:49152)+"\t"+b;d&&(c+="\t"+d);A.ctrlDelayed&&(A.ctrlDelayed=!1,r(!0,29));n.sendInput(c);A.preKey.code=b;A.preKey.down=a}}function Oa(a,b){A.ctrlDelayed&&(A.ctrlDelayed=!1,r(!0,29));n.sendInput(a+b)}function za(a,b,d,c,g){if(!J)return!1;z(k.element);c||(c=K);g||(g=V);wa[d]||(wa[d]=!0,a=(a/c|0)+w.left,b=(b/g|0)+w.top,f.beforemousedown&&f.beforemousedown(a,b,d),Oa("80",a+"\t"+b+"\t"+d))}function Ra(a){k&&k.setIMEStatus(!1);R||a.shiftKey||a.metaKey||
a.altKey||A.sendMissKey();var b=Ca(a);za(b.x,b.y,a.button);return Eb?!0:cancelDefault(a)}function Fb(a,b,d,c){d||(d=K);c||(c=V);a=(a/d|0)+w.left;b=(b/c|0)+w.top;0>a&&(a=0);0>b&&(b=0);if(f.onmousemove)f.onmousemove(a,b);w.x=a;w.y=b;Oa("82",a+"\t"+b)}function Sa(a){if(!Gb||!k||a.target!=k.element&&!wa[a.button])return!1;var b=Ca(a,k.element);!Aa||!m.isAndroid&&!m.isiOS&&W&&W.system?e&&e.__visible&&e.__setVisible(!1):oa(b.x,b.y,!0);Fb(b.x,b.y);return cancelDefault(a)}function Ba(a,b,d,c,g){c||(c=K);
g||(g=V);wa[d]=!1;a=(a/c|0)+w.left;b=(b/g|0)+w.top;0>a&&(a=0);0>b&&(b=0);Oa("81",a+"\t"+b+"\t"+d);f.aftermouseup&&f.aftermouseup(a,b,d);m.isChrome&&u&&u.waitForCopyContent()}function Ta(a){if(!J)return!1;var b=Ca(a,k.element);Ba(b.x,b.y,a.button);return Eb?!0:cancelDefault(a)}function Hb(a,b,d,c,g){c||(c=K);g||(g=V);a=(a/c|0)+w.left;b=(b/g|0)+w.top;f.onmousewheel&&f.onmousewheel(a,b,d)||Oa("83",a+"\t"+b+"\t"+d)}function $b(a,b){if(!J)return!1;for(var d=Math.abs(a),c=0>a?1:0,g=0;g<d;g++)Hb(b.x,b.y,
c);return!1}function ac(a){if(a.none)return"none";if(a.system)return a.system;if(Aa)return"none";var b;if(!(b=a.url)){var d=a.rawData;b=a.width;var c=a.height,g=document.createElement("canvas"),l=g.getContext("2d"),e=l.createImageData(b,c),f=e.data,h=b*c,p=window.devicePixelRatio||1,y=0,k=0;g.width=b;for(g.height=c;y<h;y++){var O=d[y];f[k++]=O&255;f[k++]=O>>8&255;f[k++]=O>>16&255;f[k++]=O>>24&255}l.putImageData(e,0,0,0,0,b,c);1==p?b=g.toDataURL():g.toDataURLHD?b=g.toDataURLHD():(d=document.createElement("canvas"),
l=d.getContext("2d"),d.width=b*p|0,d.height=c*p|0,l.scale(p,p),l.drawImage(g,0,0),b=d.toDataURL())}return"url("+b+") "+a.hotX+" "+a.hotY+", default"}h||(h=hi5.$("remotectrl"));if(window.svSurface&&svSurface.canvas==h&&svSurface.railWin)return svSurface.railWin.mainWin=null,window.svSurface;var m=hi5.browser,N=m.isTouch,n=null,ma=!1,K=1,V=1,Pa=0,Ib=0,cb=!1;h.style.outline="none";var F=0,G=0,B=h.getContext("2d",{alpha:!1}),D=null,M=null,R=!1,ia=!1,ra=!1,pb=!1,S=!1,H=null,aa=!0,la=!1,db=!1,ka=!1,Bb=
!1,Jb=0;this.context=B;this.fileProgress=null;this.focusTime=this.blurTime=0;var f=this,J=!0,ca=!1,ha=!1,Gb=!0,xa=null,Kb=null,P=null,e=null,W=null,ja=null,da=null,ga=0,Ia=-1,pa=-1,yb=0,zb=0,bb=!1,Va=null,w={x:0,y:0,offX:0,offY:0,left:0,top:0,right:0,bottom:0,primary:!1,isMultiMon:!1},ea=null,Ga=null,Za=0,ya,eb=!1,Lb=0,Ha=0,sa=!1;this._cr=[82,69,77,79,84,69,83,80,65,82,75];window.svSurface=this;var q=hi5.appcfg||{img:{},toolbar:{fadable:!0}};void 0==q.toolbar.draggable&&(q.toolbar.draggable=!0);var Eb=
window.clipboardData?!0:!!q.defaultEvent,Z=m.isIE||m.isEdge,Aa=Z&&!q.disableCursor,ob=m.isChromeApp||Z&&!m.isEdge||1==q.directClipAccess,Cb=!!q.forceScancode;this.setConfig=function(a){q=a};this.railWin=this.toolbar=null;this.showToolbar=this.focused=!1;this.canvas=h;this.forceTextArea=this.alwaysPaste=!1;"visible"in q.toolbar&&(this.showToolbar=q.toolbar.visible);var Ca=m.getMousePos,Da=m.calMousePos;this.getWindow=function(){return window};this.setImageCursor=function(a){Aa=a};this.setMonitor=function(a,
b,d,c){w.left=a;w.top=b;w.right=d;w.bottom=c;w.primary=0==a&&0==b;0!=d&&0!=c&&(w.isMultiMon=!1,f.setSize(d-a+1,c-b+1),w.isMultiMon=!0,Ua("hidden"),q.disableScrollbars=!0)};this.configMonitor=function(){var a=window.screenX&-4,b=window.screenY&-4;f.setMonitor(a,b,(screen.width&-4)+a-1,(screen.height&-4)+b-1)};this.isClipSynced=function(a){if(!S)return!1;var b=Date.now()-f.blurTime;if(a&&b>a)return!1;svGlobal.logger.info("clip synced in "+b);return!0};this.getScale=function(){return{x:K,y:V}};var fa=
null,Q=null,Ka=!m.isChromeApp&&!q.copyDialog&&!q.directClipAccess&&!m.isIE;this.getThumbnail=function(a){a=a||64;fa||(fa=document.createElement("canvas"));var b=Math.floor(h.height/h.width*a);fa.width!=a&&(fa.width=a);fa.height!=b&&(fa.height=b);fa.getContext("2d").drawImage(h,0,0,h.width,h.height,0,0,a,b);return fa.toDataURL()};this.initChat=function(a){var b=document.getElementById("chatWindow");hi5.Draggable(b);return new hi5.Chat(b,a)};this.equals=function(a){return h==a.canvas};this.getFreeSpace=
function(){var a=hi5.tool.getPos(h),b=window.innerWidth-a.x,a=t(window.innerHeight)-a.y,d=b>a?Math.max(hi5.browser.getScreenWidth(),hi5.browser.getScreenHeight()):Math.min(hi5.browser.getScreenWidth(),hi5.browser.getScreenHeight()),c=b>a?Math.min(hi5.browser.getScreenWidth(),hi5.browser.getScreenHeight()):Math.max(hi5.browser.getScreenWidth(),hi5.browser.getScreenHeight());b>d&&(b=d);a>c&&(a=c);return{width:b,height:a}};var L=new function(){var a=1033,b=m.isFirefox,d=m.isMacOS||m.isiOS,c=[0],g=null;
c[3]=197;c[8]=14;c[9]=15;c[12]=76;c[13]=28;c[16]=42;c[17]=29;c[18]=56;c[19]=197;c[20]=58;c[27]=1;c[32]=57;c[33]=201;c[34]=209;c[35]=207;c[36]=199;c[37]=203;c[38]=200;c[39]=205;c[40]=208;c[44]=55;c[45]=210;c[46]=211;c[48]=11;c[49]=2;c[50]=3;c[51]=4;c[52]=5;c[53]=6;c[54]=7;c[55]=8;c[56]=9;c[57]=10;c[65]=30;c[66]=48;c[67]=46;c[68]=32;c[69]=18;c[70]=33;c[71]=34;c[72]=35;c[73]=23;c[74]=36;c[75]=37;c[76]=38;c[77]=50;c[78]=49;c[79]=24;c[80]=25;c[81]=16;c[82]=19;c[83]=31;c[84]=20;c[85]=22;c[86]=47;c[87]=
17;c[88]=45;c[89]=21;c[90]=44;c[91]=219;c[92]=220;c[93]=221;c[96]=82;c[97]=79;c[98]=80;c[99]=81;c[100]=75;c[101]=76;c[102]=77;c[103]=71;c[104]=72;c[105]=73;c[106]=55;c[107]=78;c[109]=74;c[110]=83;c[111]=181;c[112]=59;c[113]=60;c[114]=61;c[115]=62;c[116]=63;c[117]=64;c[118]=65;c[119]=66;c[120]=67;c[121]=68;c[122]=87;c[123]=88;c[144]=69;c[145]=70;c[154]=183;c[166]=59;c[167]=60;c[168]=61;c[173]=66;c[174]=67;c[175]=68;c[182]=63;c[183]=62;c[216]=64;c[217]=65;c[186]=39;c[187]=13;c[188]=51;c[189]=12;c[190]=
52;c[191]=53;c[192]=41;c[219]=26;c[220]=43;c[221]=27;c[222]=40;c[224]=29;c[225]=184;c[226]=86;c[235]=123;c[255]=121;var l={Escape:1,Digit1:2,Digit2:3,Digit3:4,Digit4:5,Digit5:6,Digit6:7,Digit7:8,Digit8:9,Digit9:10,Digit0:11,Minus:12,Equal:13,Backspace:14,Tab:15,KeyQ:16,KeyW:17,KeyE:18,KeyR:19,KeyT:20,KeyY:21,KeyU:22,KeyI:23,KeyO:24,KeyP:25,BracketLeft:26,BracketRight:27,Enter:28,ControlLeft:29,KeyA:30,KeyS:31,KeyD:32,KeyF:33,KeyG:34,KeyH:35,KeyJ:36,KeyK:37,KeyL:38,Semicolon:39,Quote:40,Backquote:41,
ShiftLeft:42,Backslash:43,KeyZ:44,KeyX:45,KeyC:46,KeyV:47,KeyB:48,KeyN:49,KeyM:50,Comma:51,Period:52,Slash:53,ShiftRight:54,NumpadMultiply:55,AltLeft:56,Space:57,CapsLock:58,F1:59,F2:60,F3:61,F4:62,F5:63,F6:64,F7:65,F8:66,F9:67,F10:68,NumLock:69,ScrollLock:70,Numpad7:71,Numpad8:72,Numpad9:73,NumpadSubtract:74,Numpad4:75,Numpad5:76,Numpad6:77,NumpadAdd:78,Numpad1:79,Numpad2:80,Numpad3:81,Numpad0:82,NumpadDecimal:83,IntlBackslash:86,F11:87,F12:88,NumpadEqual:89,F13:91,F14:92,F15:93,F16:99,F17:100,F18:101,
F19:102,F20:103,F21:104,F22:105,F23:106,F24:107,KanaMode:112,Lang2:113,Lang1:114,IntlRo:115,Convert:121,NonConvert:123,IntlYen:125,NumpadComma:126,Paste:138,MediaTrackPrevious:144,Cut:151,Copy:152,MediaTrackNext:153,NumpadEnter:156,ControlRight:157,VolumeMute:160,AudioVolumeMute:160,LaunchApp2:161,MediaPlayPause:162,MediaStop:164,Eject:172,VolumeDown:174,AudioVolumeDown:174,VolumeUp:176,AudioVolumeUp:176,BrowserHome:178,NumpadDivide:181,PrintScreen:183,AltRight:184,Help:187,Pause:197,Home:199,ArrowUp:200,
PageUp:201,ArrowLeft:203,ArrowRight:205,End:207,ArrowDown:208,PageDown:209,Insert:210,Delete:211,OSLeft:219,MetaLeft:219,OSRight:220,MetaRight:220,ContextMenu:221,Power:222,BrowserSearch:229,BrowserFavorites:230,BrowserRefresh:231,BrowserStop:232,BrowserForward:233,BrowserBack:234,LaunchApp1:235,LaunchMail:236,LaunchMediaPlayer:237};this.isPrintableScancode=function(a,c){return 95<c.keyCode&&112>c.keyCode||c.altKey&&70<a&&83>a&&74!=a&&78!=a?!0:1<a&&14>a||15<a&&28>a||29<a&&42>a||42<a&&54>a||57==a};
var e=function(a){a=a.keyCode;if(b)switch(a){case 173:return 189;case 61:return 187;case 59:return 186;case 224:return 17}return a};this.converMacCtrl=!0;var f=d?function(a){switch(a){case 91:case 93:return 17;case 17:return L.converMacCtrl?91:17;case 229:return 69}return 0}:null;this.setLayout=function(b){a=b;var d=null;b="K"+b;b in h&&(d=h[b]());null===d&&(d=c);g=d;null!==g&&svGlobal.logger.info("Keyboard layout: "+a)};this.getKeyCode=function(a){var c=0;f&&(c=f(a.keyCode));c||(c=e?e(a):a.keyCode);
return c};this.getScancode=function(a){var c=0;if(a.code)c=l[a.code]||0;else{var b=L.getKeyCode(a);switch(b){case 17:c=2==a.location?157:29;break;case 16:c=2==a.location?54:42;break;case 33:c=3==a.location?73:201;break;case 34:c=3==a.location?81:209;break;case 35:c=3==a.location?79:207;break;case 36:c=3==a.location?71:199;break;case 37:c=3==a.location?75:203;break;case 38:c=3==a.location?72:200;break;case 39:c=3==a.location?77:205;break;case 40:c=3==a.location?80:208;break;case 45:c=3==a.location?
82:210;break;case 46:c=3==a.location?83:211;break;default:g&&(c=g[b]||0)}}if(d)switch(c){case 29:c=219;break;case 157:c=220;break;case 219:c=29;break;case 220:c=157}return c};this.getScancodeByKeyCode=function(a){return g?g[a]||0:0};this.getCodeTable=function(){return g};this.getLayoutCreator=function(){return h};var h=new function(){this.K3758162961=function(){var a=c.slice(0);a[244]=41;a[243]=41;a[189]=12;a[222]=13;a[220]=125;a[192]=26;a[219]=27;a[187]=39;a[186]=40;a[221]=43;a[188]=51;a[190]=52;
a[191]=53;a[226]=115;a[29]=123;a[28]=121;a[240]=112;a[242]=112;b&&(a[173]=12,a[160]=13,a[64]=26,a[59]=39,a[58]=40,e=function(a){return 220==a.keyCode&&"_"==a.key?226:a.keyCode});return a};this.K1034=this.K66570=this.K2058=this.K1040=this.K66576=function(){var a=c.slice(0);a[220]=41;a[219]=12;a[221]=13;a[186]=26;a[187]=27;a[191]=43;a[192]=39;a[189]=53;a[226]=86;b&&(e=function(a){var c=a.keyCode;a=a.key;switch(c){case 0:if("\u00e8"==a||"\u00e9"==a||"["==a)return 186;if("\u00f2"==a||"\u00e7"==a||"@"==
a)return 192;if("\u00e0"==a||"\u00b0"==a||"#"==a||"\u00f9"==a||"\u00a7"==a)return 222;break;case 60:return 226;case 160:return 221;case 171:return 187;case 173:return 189;case 222:return 219}return c});return a};this.K2057=function(){var a=c.slice(0);a[223]=41;a[222]=43;a[192]=40;a[220]=86;b&&(a[192]=41,a[173]=12,a[61]=13,a[59]=39,a[222]=40,a[163]=43);return a};this.K1031=this.K4106=this.K5130=this.K6154=this.K7178=this.K8202=this.K9226=this.K10250=this.K11274=this.K12298=this.K13322=this.K14346=
this.K15370=this.K16395=this.K17418=this.K18442=this.K19466=this.K20490=this.K99997=this.K66567=this.K2952791047=function(){var a=c.slice(0);a[220]=41;a[219]=12;a[221]=13;a[186]=26;a[187]=27;a[191]=43;a[192]=39;a[189]=53;a[226]=86;a[90]=21;a[89]=44;b?e=function(a){var c=a.keyCode,b=a.key;switch(c){case 60:return 226;case 160:return 220;case 63:return 219;case 192:return 221;case 171:return 187;case 163:return 191;case 173:return 189;case 0:if("\u00f6"==b||"\u00d6"==b&&a.shiftKey)return 192;if("\u00e4"==
b||"\u00c4"==b&&a.shiftKey)return 222;if("\u00fc"==b||"\u00dc"==b&&a.shiftKey)return 186}return c}:hi5.browser.isLinux&&(e=function(a){var c=a.keyCode;a=a.key;switch(c){case 187:if("Dead"==a)return 221;break;case 192:if("Dead"==a||"\u00b0"==a)return 220;break;case 220:return 226}return c});return a};this.K2070=function(){var a=c.slice(0);a[220]=41;a[219]=12;a[221]=13;a[186]=27;a[187]=26;a[191]=43;a[192]=39;a[189]=53;a[226]=86;return a};this.K2060=this.K99998=this.K2067=function(){var a=c.slice(0);
a[222]=41;a[219]=12;a[189]=13;a[221]=26;a[186]=27;a[77]=39;a[192]=40;a[188]=50;a[190]=51;a[191]=52;a[187]=53;a[226]=86;a[65]=16;a[90]=17;a[81]=30;a[87]=44;b&&(e=function(a){var c=a.keyCode,b=a.key;switch(c){case 60:return 226;case 169:return 219;case 173:return 189;case 160:return 221;case 164:return 186;case 165:return 192;case 59:return 190;case 58:return 191;case 61:return 187;case 0:if("\u00b2"==b||"\u00b3"==b&&a.shiftKey)return 222;if("\u00b5"==b||"`\u00b5"==b||"DeadGrave"==b||"\u00a3"==b&&a.shiftKey||
("`"==b||"``"==b)&&a.ctrlKey&&a.altKey)return 220}return c});return a};this.K3084=this.K4105=function(){var a=c.slice(0);a[222]=41;a[192]=40;a[226]=86;b&&(e=function(a){var c=a.keyCode,b=a.key;switch(c){case 0:if("\u00b0"==b||"\u00ac"==b&&a.ctrlKey&&a.altKey)return 222;if("\u00e7"==b||"\u00c7"==b&&a.shiftKey)return 221;if("\u00e0"==b||"DeadGrave"==b||"\u00c0"==b&&a.shiftKey)return 220;if("\u00e8"==b||"\u00c8"==b&&a.shiftKey)return 192;if("\u00e9"==b||"\u00c9"==b&&a.shiftKey)return 191;if("\u00f9"==
b||"\u00d9"==b&&a.shiftKey)return 226;if("DeadTilde"==b)return 221;break;case 173:return 189;case 61:return 187;case 160:return 219;case 59:return 186}return c});return a};this.K1036=function(){var a=c.slice(0);a[222]=41;a[219]=12;a[187]=13;a[221]=26;a[186]=27;a[220]=43;a[77]=39;a[192]=40;a[190]=51;a[191]=52;a[223]=53;a[226]=86;a[65]=16;a[90]=17;a[81]=30;a[87]=44;a[188]=50;b&&(e=function(a){var c=a.keyCode,b=a.key;switch(c){case 0:if("\u00b2"==b)return 222;if("\u00e7"==b||"\u00c7"==b&&a.shiftKey)return 221;
if("\u00e0"==b||"\u00c0"==b&&a.shiftKey)return 220;if("\u00e8"==b||"\u00c8"==b&&a.shiftKey)return 192;if("\u00e9"==b||"\u00c9"==b&&a.shiftKey)return 189;if("\u00f9"==b||"\u00d9"==b&&a.shiftKey)return 226;if("DeadTilde"==b)return 221;break;case 60:return 226;case 169:return 219;case 61:return 187;case 160:return 221;case 164:return 186;case 170:return 220;case 165:return 192;case 59:return 190;case 58:return 191;case 161:return 223}return c});return a};this.K4108=this.K2055=function(){var a=c.slice(0);
a[191]=41;a[219]=12;a[221]=13;a[186]=26;a[192]=27;a[223]=43;a[222]=39;a[220]=40;a[188]=51;a[190]=52;a[189]=53;a[226]=86;a[90]=21;a[89]=44;b&&(e=function(a){var c=a.keyCode,b=a.key;switch(c){case 0:if("\u00a7"==b||"\u00b0"==b&&a.shiftKey)return 191;if("\u00e0"==b||"\u00e4"==b&&a.shiftKey||"{"==b&&a.ctrlKey&&a.altKey)return 220;if("\u00e8"==b||"\u00fc"==b&&a.shiftKey||"["==b&&a.ctrlKey&&a.altKey)return 186;if("\u00e9"==b||"\u00f6"==b&&a.shiftKey)return 222;break;case 222:return 219;case 160:return 221;
case 161:return 192;case 164:return 223;case 173:return 189;case 60:return 226}return c});return a};this.K1044=this.K1083=this.K1030=function(){var a=c.slice(0);a[220]=41;a[187]=12;a[219]=13;a[221]=26;a[186]=27;a[191]=43;a[192]=39;a[222]=40;a[189]=53;a[226]=86;b&&(e=function(a){var c=a.keyCode,b=a.key;switch(c){case 0:if("\u00e5"==b||"\u00c5"==b&&a.shiftKey)return 221;if("\u00f8"==b||"\u00d8"==b&&a.shiftKey||"\u00f6"==b&&a.ctrlKey&&a.altKey)return 192;if("\u00e6"==b||"\u00c6"==b&&a.shiftKey||"\u00e4"==
b&&a.ctrlKey&&a.altKey)return 222;break;case 172:return 220;case 171:return 187;case 220:return 219;case 160:return 186;case 222:return 191;case 173:return 189;case 60:return 226}return c});return a};this.K1039=function(){var a=c.slice(0);a[220]=41;a[187]=12;a[219]=13;a[221]=26;a[186]=27;a[191]=43;a[192]=39;a[222]=40;a[189]=53;a[226]=86;b&&(e=function(a){var c=a.keyCode;a=a.key;switch(c){case 0:if("Dead"==a)return 220;if("\u00f6"==a||"\u00d6"==a||"\\"==a)return 187;if("\u00f0"==a||"\u00d0"==a)return 221;
if("\u00e6"==a||"\u00c6"==a)return 192;if("\u00fe"==a||"\u00de"==a)return 189;break;case 173:return 219;case 222:return"Dead"==a||"'"==a?222:186;case 171:return 191;case 60:return 226}return c});return a};this.K1053=function(){var a=c.slice(0);a[220]=41;a[187]=12;a[219]=13;a[221]=26;a[186]=27;a[191]=43;a[192]=39;a[222]=40;a[189]=53;a[226]=86;b&&(e=function(a){var c=a.keyCode,b=a.key;switch(c){case 0:if("\u00a7"==b||"\u00bd"==b&&a.shiftKey)return 220;if("\u00e5"==b||"\u00c5"==b&&a.shiftKey)return 221;
if("\u00f8"==b||"\u00d8"==b&&a.shiftKey||"\u00f6"==b&&a.ctrlKey&&a.altKey)return 192;if("\u00e4"==b||"\u00c4"==b&&a.shiftKey)return 222;break;case 171:return 187;case 192:return 219;case 160:return 186;case 222:return 191;case 173:return 189;case 60:return 226}return c});return a};this.K1055=function(){var a=c.slice(0);a[220]=52;a[223]=12;a[189]=13;a[191]=51;a[188]=43;a[190]=53;a[226]=86;b&&(e=function(a){var c=a.keyCode,b=a.key;switch(c){case 0:if("\u011f"==b||"\u011e"==b&&a.shiftKey||a.ctrlKey&&
a.altKey&&"BracketLeft"==a.code)return 219;if("\u00fc"==b||"\u00dc"==b&&a.shiftKey||a.ctrlKey&&a.altKey&&"BracketRight"==a.code)return 221;if("\u015f"==b||"\u015e"==b&&a.shiftKey||a.ctrlKey&&a.altKey&&"Semicolon"==a.code)return 186;if("\u00f6"==b||"\u00d6"==b&&a.shiftKey)return 191;if("\u00e7"==b||"\u00c7"==b&&a.shiftKey)return 220;break;case 73:return 222;case 60:return 226;case 173:return 189;case 170:return 223;case 162:return 192}return c});return a};this.K6153=function(){var a=c.slice(0);a[223]=
41;a[189]=12;a[187]=13;a[219]=26;a[221]=27;a[186]=39;a[192]=40;a[222]=43;a[220]=86;a[188]=51;a[190]=52;a[191]=53;return a}}};this.getKeyboardMgr=function(){return L};var u=new function(){function a(a,c){var b=u.parseClipData(c);if(!(q.copyTextOnly&&"text/plain"!=b.type||u.processFileGroup(b)))if(m.isEdge&&"text/plain"!=b.type)k.resetCSS(),k.setValue(b.value),k.select(),setTimeout(function(){k.setValue("");M&&M.setValue("");k.restoreCSS();u.processImgCopy(b.value)},555);else{if("text/plain"!=b.type){var d=
hi5.browser.html2text(b.value);d&&a.clipboardData.setData("text/plain",d);u.processImgCopy(b.value)}a.clipboardData.setData(b.type,b.value);a.preventDefault()}}function b(){u&&(u.copyContent&&(u.copyToClipboard(u.copyContent.type,u.copyContent.value),u.copyContent=null),u.waitingCopyContent=!1)}this.hasCopyCmd=document.queryCommandSupported("copy");this.hasPasteCmd=document.queryCommandSupported("paste");this.pasteEventFired=!1;this.release=function(){u.clipData=null};this.clipData=null;this.paste=
function(a,c){var b=new C,d=0,e=null,f=window.clipboardData||c.clipboardData,h=window.clipboardData?f.getData("Text"):f.getData("text/plain"),k="",m="",k=0;f.types&&(m=f.getData("text/html"));m&&!h&&(h=hi5.browser.html2text(m));h&&b.setData("text/plain",h);if(q.pasteTextOnly)c.preventDefault(),a(b);else{var n=f.items;if(n)for(d=0,k=n.length;d<k;d++){if("image/png"==n[d].type){e=n[d].getAsFile();break}}else if(f.files)for(n=f.files,d=0,k=n.length;d<k;d++)if(-1!=n[d].type.indexOf("image/png")){e=n[d];
break}if(e)d=new FileReader,c.preventDefault(),d.onloadend=function(c){c.target.readyState==FileReader.DONE&&(c=hi5.Base64.enc(new Uint8Array(c.target.result)),b.setData("image/png",c),a(b))},d.readAsArrayBuffer(e);else if(h){if(f.types){e=f.types.indexOf?-1!=f.types.indexOf("text/rtf"):f.types.contains("text/rtf");if(k=f.getData("text/rtf"))0==k.charCodeAt(k.length-1)&&(k=k.substring(0,k.length-1)),b.setData("text/richtext",k);m&&(d=m.lastIndexOf("</html>"),d+7<m.length&&(m=m.substring(0,d+7)),b.setData("text/html",
m));if(!hi5.browser.isEdge&&(!e||k||m)){c.preventDefault();a(b);return}}if("TEXTAREA"==c.target.nodeName)c.preventDefault(),document.queryCommandSupported("paste")&&(b=u.getClipContent(b)),a(b);else{D&&(D.disableTextInput=!0);M&&(M.disableTextInput=!0);c.target.innerHTML="";var r=c.target.style.opacity;c.target.style.opacity=0;setTimeout(function(){var d=c.target.innerHTML;d&&d!=h&&(b.setData("text/html","<body>"+d+"</body>"),D?D.init():c.target.innerHTML="");a(b);c.target.style.opacity=r;D&&(D.disableTextInput=
!1);M&&(M.disableTextInput=!1)},300)}}else c.preventDefault(),a(b)}};this.onCopy=function(b){if(b.target==k.element){J&&aa||cancelDefault(b);var c="copy"==b.type?46:45,d="copy"==b.type?67:88;ka||(r(!0,29),ba(!0,d,c),ba(!1,d,c),r(!1,29));m.isMacOS&&ba(!1,d,c);aa&&!ob&&la&&(999<Date.now()-Jb&&(c=n.getClipData(b.type),a(b,c),u.clipData=null,S=!0),Jb=Date.now(),svGlobal.logger.info("clip synced: true"))}};this.onPaste=function(a){if(a.target==k.element){Ma&&Ma.cancelCtrlV();if(!J||!aa)return cancelDefault(a);
db||(S=!0);if(!f.alwaysPaste&&S){var c=!0;f.onclipdata&&(c=!f.onclipdata(u.clipData,!0));c&&setTimeout(Na,300);svGlobal.logger.info("Ctrl+V only");return cancelDefault(a)}S=!0;u.paste(Zb,a);return!0}};this.parseClipData=function(a){var c=a.indexOf(";"),b=a.substring(0,c);a=a.substring(c+1);return{type:b,value:a}};this.getClipContent=function(a){if(!document.queryCommandSupported("paste"))return a;var c=Xa(q.pasteTextOnly?"textarea":"div");c.focus();try{if(document.queryCommandEnabled("paste")&&document.execCommand("paste"))return a||
(a=new C),q.pasteTextOnly||a.setData("text/html","<body>"+c.innerHTML+"</body>"),-1==a.types.indexOf("text/plain")&&a.setData("text/plain",q.pasteTextOnly?c.value:c.innerText||c.innerHTML.replace(/<br>/gi,"\n").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&lt;/gi,"<").replace(/&gt;/gi,">")),a}finally{f.focused=!0,c.parentNode.removeChild(c),k&&k.focus()}return a};this.accessClip=function(a){document.queryCommandSupported("paste")||a(null);var c=Xa(q.pasteTextOnly?
"textarea":"div");c.focus();c.addEventListener("paste",function(b){b.stopPropagation();u.pasteEventFired=!0;u.paste(function(b){f.focused=!0;c.parentNode&&c.parentNode.removeChild(c);k&&k.focus();a(b)},b)},!1);u.pasteEventFired=!1;document.queryCommandEnabled("paste")&&document.execCommand("paste")&&u.pasteEventFired||setTimeout(function(){S=!0;u.pasteEventFired||a(null);f.focused=!0;c.parentNode&&c.parentNode.removeChild(c);k&&k.focus()},55)};this.getContent=function(){var a=u.getClipContent();k&&
k.element.removeEventListener("click",u.getContent,!1);return a&&!a.equals(u.clipData)?(u.clipData=a,n.send("880text/plain,text/html\t0"),!0):!1};this.startPasteCmd=function(){k&&document.queryCommandSupported("paste")&&k.element.addEventListener("click",u.getContent)};this.waitingCopyContent=!1;this.copyContent=null;this.waitForCopyContent=function(){u.waitingCopyContent=!0;setTimeout(b,700)};this.prePaste=function(){S||!document.queryCommandEnabled("paste")&&!window.clipboardData||u.accessClip(function(a){if(a){var b=
0===a.types.length||a.equals(u.clipData),d=b?"":a.types.join(",");b||(-1!=d.indexOf("text/html")&&-1==d.indexOf("text/richtext")&&(d+=",text/richtext"),b=(b=a.getData("text/plain"))?b.hashCode():0,n.send("880"+d+"\t"+b),u.clipData=a,S=!0)}})};this.copyToClipboard=function(a,b){var c="text/plain"==a?"textarea":"div",d=Xa(c,!1),e=!1,h=0<b.indexOf("data-sv-img");if(window.clipboardData&&"text/plain"==a)window.clipboardData.setData("Text",b),e=!0;else{if("div"==c)if(d.innerHTML=b,d.focus(),h&&document.body.createControlRange){var n=
document.body.createControlRange();n.add(d.childNodes[0]);h=!1}else m.selectEditable(d);else d.value=b,d.focus(),d.select();try{e=n?n.execCommand("Copy"):document.execCommand("copy",!1,null)}catch(p){}finally{f.focused=!0,d.parentNode.removeChild(d),k&&k.focus()}}S=!0;if(!e&&f.beforeCopyDialog&&f.beforeCopyDialog(b,__svi18n.info.imgCopyDownload,a))return!0;c=h&&u.processImgCopy(b);e||!c&&__svi18n.info.userCopy&&f.showMessage({title:__svi18n.info.userCopy,msg:b,timeout:9999,select:!0,format:a});return e};
this.processFileGroup=function(a){if("application/x-filegroup"==a.type){a=a.value.split("\r\n");var b="",d=0;a.forEach(function(a){a=a.split("\t");1<a.length&&(b&&(b+=","),b+=a[0],d+=parseInt(a[1],10))});28<b.length&&(b=b.substring(0,28)+"...");b=b+"<br>Total: "+hi5.tool.bytesToSize(d)+" Qty:"+a.length;__svi18n.info.download&&f.showMessage({title:__svi18n.info.download,msg:b,timeout:9E3,cbYes:function(){this.destroy();H.download()},cbNo:function(){this.destroy()}});return!0}return!1};this.processImgCopy=
function(a){return 0<a.indexOf("data-sv-img")&&__svi18n.info.imgCopyDownload?(f.showMessage({title:__svi18n.info.imgCopyDownload,msg:a,timeout:9999}),!0):!1}},Ja=m.isMacOS||m.isiOS,A=new function(){this.afterComposition=this.onComposition=this.ctrlDelayed=this.noKeyStuck=!1;this.preKey={code:0,down:!1};this.preScancode={code:0,down:!1};var a=!1,b=!1,d=!1,c={};this.sendMissKey=function(){for(var a in c)c[a]&&r(!1,parseInt(a,10))};this.isKeyDown=function(a){return c[a]};this.isKeyDownSent=function(a,
b){var d=!0;a||(d=c[b]);c[b]=a;return d};this.check=function(a){var b=L.getKeyCode(a),c="keydown"==a.type;if(n.checkLockFlags&&144!=b&20!=b&&145!=b&&c&&a.getModifierState&&n.sendKeyboardSyncFlags){var d=0;a.getModifierState("CapsLock")&&(d|=4);Ja||m.isCrOS?d|=n.localLockFlags&2:a.getModifierState("NumLock")&&(d|=2);a.getModifierState("ScrollLock")&&(d|=1);a=d;d=a!=n.localLockFlags||a!=n.remoteLockFlags;n.checkLockFlags=!1;d&&(svGlobal.logger.info("sync lock key, current:"+a+" local:"+n.localLockFlags+
" remote:"+n.remoteLockFlags),n.sendKeyboardSyncFlags(a)||(n.checkLockFlags=!0))}17==b&&(R=c)};this["continue"]=function(c,e,f){if(29==e&&c)return A.ctrlDelayed=!0,!1;if(A.ctrlDelayed||Ja&&c)if(184==e)A.ctrlDelayed=!1,d=b=!0;else if(A.ctrlDelayed)return A.ctrlDelayed=!1,b||r(!0,29),!0;if(29==e){if(b&&!c)return!1}else if(184==e&&b)return c||(b=!1,a=!0,d&&f&&(r(!0,184),r(!1,184),d=!1)),f?!1:!0;return!0};this.isAltGr=function(c,e){return b?(d=!1,!0):a?(a=!1,c?!1:!0):!1}};this.requestCredential=function(a,
b){q.closeOnDisconn=!1;var d=__svi18n.template.login;if(d){var c=document.createElement("div");c.className="appdlg";c.innerHTML=d;document.body.appendChild(c);(d=hi5.$("loginDomain"))&&a.nbDomain&&(d.innerHTML=a.nbDomain);var g=new hi5.ui.Lightbox(c);g.onclose=function(){document.body.removeChild(c)};g.show();(d=hi5.$("loginUser"))&&d.focus();if(d=hi5.$("frmLogin"))d.onsubmit=function(){var a=hi5.$("loginUser").value,c=hi5.$("loginPassword").value,d=hi5.$("loginDomain").innerHTML;g.dismiss();setTimeout(function(){b(a,
c,d)},5);return!1}}else f.showMessage("No value for login template")};var k=null;if(N)rb();else{var fb=hi5.$("tmContainer");fb&&fb.parentNode.removeChild(fb)}N&&!q.toolbar.draggable&&window.addEventListener("scroll",function(){setTimeout(function(){if(Q){var a=hi5.$("pc_key");a&&(a.style.top=window.pageYOffset+"px",a.style.left=window.pageXOffset+"px")}f.toolbar&&(f.toolbar.style.top=window.pageYOffset+"px",f.toolbar.style.left=window.pageXOffset+.45*window.innerWidth+"px")},200)},!1);this.setCaretPos=
function(a,b){};this.showMessage=function(a,b){a&&q.displayMsg&&hi5.notifications.notify("string"==typeof a?{msg:a,timeout:b||0}:a)};this.hideWhenClose="hideWhenClose"in q?q.hideWhenClose:!0;this.setReadOnly=function(a,b){Gb=(J=!a)||!0===b};this.setPlayerMode=function(){ha=!0;f.showToolbar=!1;f.setReadOnly(!0);f.hideWhenClose=!1};this.setAutoScale=function(a){var b="autoScale"in q;b&&(a=q.autoScale);a?(va(!0),Ua("hidden")):b||va(!1);ma=a};Aa&&ua(q.cursorNameOnly);this.setTouchpad=function(a){ca=a;
var b=hi5.$("touchpadMode");b&&(b.checked=a,b.onchange=function(a){ca=a.target.checked});a&&(e||ua(q.cursorNameOnly))};this.setExtKeyboard=function(a){if(N){k.adjust(!0);k.setContentEditable(a?"true":"false");ga=a?1:0;m.isChrome&&k.setFontSize("2em");a&&k.focus();var b=hi5.$("extKBD");b&&b.checked!=a&&(b.checked=a)}};this.focus=function(){k&&z(k.element)};this.getInputElement=function(){return k};this.scaleTo=function(a,b,d){Pa=a;Ib=b;cb=d;h&&50<F&&(a/=F,b/=G,cb?(K=a,V=b):V=K=b=a=Math.min(a,b),hi5.tool.scale(h.parentNode,
a,b))};this.setSize=function(a,b,d){w.isMultiMon||(w.right!=w.left+a-1&&(w.right=w.left+a-1,w.bottom=w.top+b-1),F=a,G=b,ma||Ua(d),h.width=F,h.height=G,n?f.drawText(__svi18n.wait):(B.save(),B.fillStyle="white",B.fillRect(0,0,F,G),B.restore()),ma?va(!0):Pa&&Pa!=a&&f.scaleTo(Pa,Ib,cb),N&&rb(),k||(k=new ib),k.adjust(),P&&P.visible()&&P.dismiss())};this.reposition=function(){k.adjust()};this.setController=function(a){n=a;ya=a.draw;n.sendInput||(n.sendInput=n.send);N&&m.setOrientaionHandler(function(){window.innerWidth>
window.innerHeight!=F>G&&(ma?va(!0):(clearTimeout(Kb),Kb=setTimeout(function(){window.innerWidth>window.innerHeight!=F>G&&(n.onorientationchange({svSurface:f,innerWidth:window.innerWidth,innerHeight:t(window.innerHeight)}),q.disableScoll||window.scrollTo(0,0))},555)))})};this.setFileHandler=function(a){"FileReader"in window||(a=null);if(a){if(!H&&!ha)if(H=a,H.addEvent("uploaded",function(a,b){!a&&hi5.$("filecontainer")&&Lb&16&&(hi5.$("__cancelUpload")&&(hi5.$("__cancelUpload").style.visibility="hidden"),
f.fileProgress.maxValue=0,f.fileProgress.style.display="none",f.refreshFiles(),__svi18n.file.uploadDone&&f.showMessage(__svi18n.file.uploadDone+" "+hi5.tool.bytesToSize(b.size/(b.duration/1E3))+"/s",5E3))}),H.addEvent("uploadstarted",function(a){a&&setTimeout(Na,999)}),hi5.$("filecontainer")){hi5.$("filecontainer").className="h5-form";f.fileProgress=new hi5.ProgressBar(hi5.$("total"));var b=hi5.$("__cancelUpload");b&&b.addEventListener("click",function(){H.cancelAll()},!1);H.addEvent("beforeupload",
function(a,c,g){g||(b&&(b.style.visibility="visible"),f.fileProgress.style.display="block",f.fileProgress.maxValue+=a.size)});H.addEvent("progress",function(a){f.fileProgress.setProgress(a)})}else Wa()}else H=null,f.fileProgress=null,Wa(),ea&&(ea.release(),ea=null);tb();Tb()};this.setFeature=function(a){Lb=a;var b,d=!(a&16),c=!(a&65536);(d||ha)&&Wa();a&128&&(b=hi5.$("uploadfile"))&&(b.style.visibility="hidden");a&131072&&((b=hi5.$("__sv_download__"))&&b.parentNode.removeChild(b),(b=hi5.$("__sv_view__"))&&
b.parentNode.removeChild(b));a&256||(b=hi5.$("shadowing"))&&b.parentNode.removeChild(b);a&1024||(b=hi5.$("ssParent"))&&b.parentNode.removeChild(b);(c&&d||ha)&&f.setFileHandler(null)};var Ya=new function(){function a(){if(0===d.length){if(c=!1,!g){var a=hi5.$("_sv_pdf_parent");a&&e&&e.visible()&&e.dismiss();setTimeout(function(){a&&a.parentNode&&a.parentNode.removeChild(a)},9999)}}else b()}function b(){var b=d.shift();if(b){var f=hi5.$("_sv_pdf_parent"),h=__svi18n.info.printready||"Your document is ready.",
b=(g=m.isAndroid||m.isiOS||!!q.showPDFLink)?'<p style="text-align:center;line-height:4em"><a href="'+b+'" target="_blank">'+h+"</a></p>":(m.isChromeApp?"<webview":"<iframe")+' src="'+b+'" width="100%" height="100%" id="_iFramePDF">'+(m.isChromeApp?"</webview>":"</iframe>");f&&f.visible&&f.visible()&&f.dismiss&&f.dismiss();f&&f.parentNode&&f.parentNode.removeChild(f);f=document.createElement("div");f.style.backgroundColor="white";f.style.width=g?"30%":"70%";f.style.height=g?"4elm":"70%";f.id="_sv_pdf_parent";
g&&(f.style.overflow="scroll");f.innerHTML=b;document.body.appendChild(f);e=new hi5.ui.Lightbox(f,{close:{top:"-20px",right:"-15px"}});e.onclose=a;e.show()}c=!0}var d=[],c=!1,g=!1,e=null;this.clearPDF=function(){a()};this.showPDF=function(a){d.push(a);c||b()}};this.close=function(){eb=!1;if(n&&(svGlobal.logger.info("close ui..."),J=!1,Ha&&cancelAnimationFrame(Ha),Fa(),Rb(),u&&(u.release(),u=null),Ga&&(Ga.release(),Ga=null),ea&&(ea.release(),ea=null),M&&(M.release(),M=null),n=ya=ja=W=e=P=H=M=fa=A=
L=null,f.fileProgress=null,Ya.clearPDF(),ma&&f.setAutoScale(!1),Q&&(Q.setVisibility(!1),Q=null),"clearScreen"in q&&!q.clearScreen||B.fillRect(0,0,h.width,h.height),window.svSurface=null,pb=!0,window&&!ha)){try{if(0<hi5.notifications.notifySize()){hi5.notifications.onempty=function(){f.close();hi5.notifications.onempty=null};return}if(q.closeOnDisconn)window.close();else if(this.hide(),m.isChromeApp){var a=chrome.app.window.current();a&&!q.disableMaxFullScn&&(a.onMaximized.removeListener(jb),a.isFullscreen()&&
(a.restore(),a.restore()))}}catch(b){}f=h=B=f.context=null;svGlobal.logger.info("closed ui")}};this.setFastCopy=function(a){};this.drawLicense=function(a){if(0!=q.drawLicense){var b=a.charAt(0);B.save();B.font="12pt Arial";B.fillStyle="W"==b?"red":"black";a=a.substring(1);B.fillText(a,10,G-24);B.restore()}};this.drawText=function(a){var b=q.text||{};B.save();var d=h.width,c=h.height;B.fillStyle=b.backgroundFillStyle||"white";B.fillRect(0,0,d,c);var e=20,f=50;"center"==b.textAlign&&(e=d/2,f=c/2);B.font=
b.font||"18pt Arial";B.fillStyle=b.fillStyle||"black";b.textAlign&&(B.textAlign=b.textAlign);b.textBaseline&&(B.textBaseline=b.textBaseline);B.fillText(a,e,f);B.restore()};this.showPDF=function(a){Ya.showPDF(a)};this.hide=function(){f.hideWhenClose&&(h.height=1,h.width=1);k&&k.hide()};var Mb=0;this.copyToClip=function(a,b){if(aa&&la){var d=u.parseClipData(a);if(!(q.copyTextOnly&&"text/plain"!=d.type||u.processFileGroup(d)))if(u.waitingCopyContent)u.copyContent=d;else{var c=d.value;(0<c.indexOf("<img ")||
q.copyDialog)&&!u.hasCopyCmd||u.copyToClipboard(d.type,c)}}};this.fullScreen=function(){h.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)};Q=new function(){function a(){d&&(R?hi5.html.addClass(d,"button_selected"):hi5.html.removeClass(d,"button_selected"));c&&(ia?hi5.html.addClass(c,"button_selected"):hi5.html.removeClass(c,"button_selected"));e&&(ra?hi5.html.addClass(e,"button_selected"):hi5.html.removeClass(e,"button_selected"))}function b(b){b=b.target;var g=b.innerHTML,g=g.replace(/\u2190/g,
"left").replace(/\u2191/g,"up").replace(/\u2192/g,"right").replace(/\u2193/g,"down");switch(g){case "Ctrl":d||(d=b);R?r(!1,29):r(!0,29);R=!R;a();break;case "Alt":c||(c=b);ia?r(!1,56):r(!0,56);ia=!ia;a();break;case "Shift":e||(e=b);ra?r(!1,42):r(!0,42);ra=!ra;a();break;case "...":if(b=hi5.$("pc_key_more"))b.style.display="block"==b.style.display?"none":"block";break;case "Start":g="Ctrl+Esc";default:f.writeKeyComb(g),Q.resetModifier()}}var d=null,c=null,e=null,h={ctrl:!1,alt:!1,shift:!1};this.setStickyKey=
function(a){h=a};this.setVisibility=function(a){if(a){if(ga=Date.now(),a=hi5.$("pc_key"))a.style.display="block",a.style.top=window.pageYOffset+"px",M&&(M.setValue("`\t`"),M.select())}else if(ga=0,a=hi5.$("pc_key"))a=hi5.$("shortcuts"),a&&a.checked||(k.style.display="none")};this.resetModifier=function(){ia&&!h.alt&&(ia=!1,r(!1,56));R&&!h.ctrl&&(R=!1,r(!1,29));ra&&!h.shift&&(ra=!1,r(!1,42));a()};var k=hi5.$("pc_key");if(k){var n=k.getElementsByTagName("span"),q=n.length,p=m.isFirefox?"mousedown":
"touchstart";"ontouchstart"in window||(navigator.pointerEnabled?p="pointerdown":navigator.msPointerEnabled&&(p="MSPointerDown"));for(var u=0;u<q;u++){var t=n[u];t.className="button";t.addEventListener(p,b,!1);"mousedown"!=p&&t.addEventListener("mousedown",b,!1)}k.style.position="absolute"}};this.setStickyKey=function(a){Q.setStickyKey(a)};var Nb=hi5.$("shortcuts");Nb&&Nb.addEventListener("change",function(a){Q.setVisibility(a.target.checked)});this.setKeysVisibility=function(a){Q&&Q.setVisibility(a)};
this.setDirectory=function(a){var b=hi5.$("parentPath");b&&"."!=a&&(b.currentDir=a)};this.refreshFiles=function(){P&&P.visible()?na(".",P):sb(null)};this.showConnectonInfo=function(){var a=n.getAppInfo(),b=hi5.$("numericId");b&&(b.innerHTML=a.numericId);if(b=hi5.$("connectingTo"))b.innerHTML=a.server;if(b=hi5.$("joinLink"))b.href=b.innerHTML=a.joinLink;a=new hi5.ui.Lightbox(hi5.$("appinfo"));a.show();k&&(k.element.oncontextmenu=null,k.element.onselectstart=null);a.onclose=qb};this.processLink=function(a){function b(b){window.open(a);
b.target.parentNode.removeChild(b.target)}if(!f.beforeOpenLink||!f.beforeOpenLink(a)){clearTimeout(Mb);var d=f.toolbar,c=d.getButton("_svLinkInfo");c?c.onclick=b:(c=d.addButton(q.img.link?q.img.link:"link.png",b),c.id="_svLinkInfo");c.title=a;d.startFade();Mb=setTimeout(function(){f.toolbar.removeButton("_svLinkInfo")},1E4)}};this.setUnicode=function(a){k&&(!a&&N&&(m.isiOS||m.isAndroid)&&(a=!0),svGlobal.logger.info("Unicode:"+a),D.onkeydown=D.onkeyup=a?Vb:Xb,D.ontextinput=a?Yb:null,D.unicode=a)&&
(D.oncomposition=Wb)};this.forceScancode=function(a){Cb=a};this.setTouchRemoting=function(a){!0===a?(ja=new ta(f,h),svGlobal.logger.info("touch remoting"),__svi18n.info.touchremoting&&f.showMessage(__svi18n.info.touchremoting)):ja=new hb(f)};this.setClipboard=function(a,b,d){(aa=a)?(la=void 0==b?!0:b,db=void 0==d?!0:d):db=la=!1;Ka=a?!m.isChromeApp&&!q.copyDialog&&!q.directClipAccess&&!m.isIE:!1};this.setJoinMode=function(a){n.setJoinMode(a)};this.requestControl=function(){n.requestControl()};this.repaint=
function(a,b,d,c){w.isMultiMon?(a<w.left&&(a=w.left),b<w.top&&(b=w.top),d>w.right&&(d=w.right),c>w.bottom&&(c=w.bottom),a<=w.right&&b<=w.bottom&&(a=n.refresh(a,b,d,c))&&B.putImageData(a.imgData,a.left-w.left,a.top-w.top,0,0,a.width,a.height)):(a=n.refresh(a,b,d,c))&&B.putImageData(a.imgData,a.left,a.top,0,0,a.width,a.height)};this.running=function(){return eb};this.run=function(a,b,d){function c(a){a.target.removeEventListener("click",c,!1);n.send("884")}L.converMacCtrl=!1!==b;A.noKeyStuck=!!d;eb=
!0;k||(k=new ib);k.adjust();hi5.notifications.clearAll();3758162961!=a&&3758162962!=a||!k||k.setContentEditable("false");L.setLayout(a);a=-1!=[99997,99998,99999].indexOf(a);void 0==q.closeOnDisconn&&(q.closeOnDisconn=!!window.opener&&!m.isChromeApp);q.disableScoll||window.scrollTo(0,0);tb();Sb();b=k.element;ha||(ja=new hb(f),d=new x(b),d.ontouch=Ub,d.onmousedown=Ra,d.onmousemove=Sa,d.onmouseup=Ta,b.addEventListener("mouseleave",Ea,!1),b.addEventListener("mouseenter",Ea,!1),U(b,$b,!1),b.addEventListener("paste",
u.onPaste,!1),aa&&Ka&&la&&(b.addEventListener("copy",u.onCopy,!1),b.addEventListener("cut",u.onCopy,!1)));!1!==q.autoFocus&&z(b);f.setUnicode(a);this.drawText(__svi18n.wait);if(f.onstart)f.onstart(h);b.addEventListener("click",c,!1);ya&&(Ha=requestAnimationFrame(vb));k.adjust();q.disableScoll||window.scrollTo(0,0)};var wb=q.animation||42;m.isIE&&(wb*=2);this.moveCursorBy=this.movCursorBy=xb;this.moveCursor=function(a,b,d,c,g,f){a-=w.left;b-=w.top;0>a||0>b||a>=F||b>=G||(e||ua(q.cursorNameOnly),e.__visible||
e.__setVisible(!0),e.scrX=a,e.scrY=b,c&&9<c.length&&(c=c.substring(0,9)),e.moveCursor(a+w.offX,b+w.offY,c,g,f),J&&!d&&n.sendInput("82"+a+"\t"+b),w.x=a,w.y=b)};this.switchSoftKeyboard=$a;this.isSoftKeyboardOn=function(){return sa};var Ob=hi5.$("svTouchInput");Ob&&Ob.addEventListener("click",function(){$a()},!1);this.touchstart=function(a){switch(a.pointes){case 1:ca?(e||ua(q.cursorNameOnly),ab("touchstart",a.screenX,a.screenY,!a.flick)):a.flick&&!Y()||za(a.x,a.y,0);break;case 2:Ia=a.screenX,pa=a.screenY}};
this.touchmove=function(a){switch(a.pointes){case 1:ca?ab("touchmove",a.screenX,a.screenY,!a.flick):a.flick&&!Y()||Fb(a.x,a.y);break;case 2:19<Math.abs(a.screenY-pa)&&(Hb(a.x,a.y,0<a.screenY-pa?0:1),Ia=a.screenX,pa=a.screenY)}};this.touchend=function(a){switch(a.pointes){case 1:ca?ab("touchend",a.screenX,a.screenY,!a.flick):(oa(a.x,a.y,!0),a.flick&&!Y()||Ba(a.x,a.y,0));break;case 2:if(!a.moved){var b=ca?e.scrX:a.x;a=ca?e.scrY:a.y;oa(b,a);za(b,a,2);Ba(b,a,2)}break;case 3:if(a.gesture)switch(a.gesture){case "OPEN":r(!0,
219);r(!0,200);r(!1,200);r(!1,219);break;case "CLOSE":r(!0,219);r(!0,208);r(!1,208);r(!1,219);break;case "LEFT":r(!0,56);r(!0,1);r(!1,1);r(!1,56);break;case "RIGHT":r(!0,42);r(!0,56);r(!0,1);r(!1,1);r(!1,56);r(!1,42);break;case "UP":r(!0,42);r(!0,219);ba(!0,77,50);ba(!1,77,50);r(!1,219);r(!1,42);break;case "DOWN":r(!0,219),ba(!0,77,50),ba(!1,77,50),r(!1,219)}else $a()}};this.flick=function(a){switch(a.from){case 4:n.sendInput("840\t209");n.sendInput("8449152\t209");break;case 2:n.sendInput("840\t201"),
n.sendInput("8449152\t201")}};this.longpress=function(a){ca&&(a.pointes=2);switch(a.pointes){case 1:var b=a.x;a=a.y;oa(b,a);za(b,a,2);Ba(b,a,2);break;case 2:e&&(za(e.scrX,e.scrY,2,1),Ba(e.scrX,e.scrY,2,1))}};this.redirectTouches=function(a){if(J){for(var b=a.length,d,c="90"+b,e=0;e<b;e++)d=a[e],c=c+"\t"+d.contactId+";"+d.contactFlags+";"+Math.floor(d.x/K)+";"+Math.floor(d.y/V);n.send(c)}};var La=0;this.setIgnorePaste=function(a){S=a};this.processClipReq=function(a){if(!aa)return n.send("881ERROR\t"),
!0;var b=u.clipData;if(b||S)return Db(b,a),!0;u.accessClip(function(b){Db(b,a)});return document.queryCommandSupported("paste")};var Ma=Z?new function(){var a;this.sendCtrlVLater=function(){a=setTimeout(Na,333)};this.cancelCtrlV=function(){clearTimeout(a)};return this}:null,wa={};this.getMousePosition=function(){return w};this.writeKeyComb=function(a){n.writeKeyComb(a)};this.setCursor=function(a){a&&!q.disableCursor&&(W=a,e&&e.setCursor(a),e&&Aa&&!a.system&&(e.__setVisible(!0),oa(w.x,w.y,!0)),ha||
(a.result||(a.result=q.cursorNameOnly?"none":ac(a)),k?k.element.style.cursor=a.result:h.style.cursor=a.result))};this.setVisible=function(a,b){var d=a?"visible":"hidden";"number"==typeof b?setTimeout(function(){h.style.visibility=d},b):h.style.visibility=d};this.initWhiteboard=function(a,b){var d=h.parentNode,c=d.querySelector('canvas[name="svWhiteboard"]');if(!c){c=document.createElement("canvas");c.setAttribute("name","svWhiteboard");c.width=a||F;c.height=b||G;c.style.zIndex=80;var e=k.element;
c.style.position=e.style.position;c.style.left=e.style.left;c.style.top=e.style.top;d.appendChild(c)}return c};this.removeWhiteboard=function(){var a=h.parentNode,b=a.querySelector('canvas[name="svWhiteboard"]');b&&a.removeChild(b)}}svGlobal.LocalInterface||(svGlobal.LocalInterface=LocalInterface);
svGlobal.rdpFile={loadRdpFile:function(h,t){var z=t.elements,C=h.split("\r\n");2>C.length&&(C=h.split("\n"));if(2>C.length)return!1;var I=hi5.$("gateway"),U=I.value;t.reset();I.value=U;I=0;for(U=C.length;I<U;I++){var x=C[I],Y=x.indexOf(":"),ta=x.substring(0,Y),x=x.substring(Y+3),ta=ta.toLowerCase();switch(ta){case "full address":Y=x.indexOf(":");0<Y?(z.server.value=x.substring(0,Y),z.port.value=x.substring(Y+1)):z.server.value=x;break;case "username":z.user.value=x;break;case "domain":z.domain.value=
x;break;case "connect to console":z.useConsole.checked="0"!=x;break;case "desktopwidth":z.width.value=x;break;case "desktopheight":z.height.value=x;break;case "session bpp":z.server_bpp.value=x;break;case "audiomode":z.playSound.value=x;break;case "alternate shell":0<x.length&&(z.command.value=x,hi5.$("app").checked||(hi5.$("shell").checked=!0));break;case "shell working directory":z.directory=x;break;case "redirectclipboard":z.mapClipboard.checked="0"!=x;break;case "redirectprinters":z.mapPrinter.checked=
"0"!=x;break;case "server port":0<x.length&&(z.port.value=x);break;case "disable wallpaper":z.background.checked="0"==x;break;case "disable themes":z.styles.checked="0"==x;break;case "disable menu anims":z.animation.checked="0"==x;break;case "disable full window drag":z.contents.checked="0"==x;break;case "allow font smoothing":z.smoothfont.checked="0"!=x;break;case "allow desktop composition":z.composition.checked="0"!=x;break;case "bitmapcachepersistenable":z.bitmap.checked="0"!=x;break;case "remoteapplicationprogram":z.exe.value=
x;break;case "remoteapplicationcmdline":z.args.value=x;break;case "remoteapplicationmode":hi5.$("app").checked="1"==x;break;case "loadbalanceinfo":z.loadBalanceInfo.value=x}}return!0},handleFiles:function(h,t){if(1!=h.length)hi5.notifications.notify({msg:"Please one file only"});else{var z=h[0],C=z.name,I=C.length;if(4<I&&".rdp"==C.substring(I-4).toLowerCase()){var U=new FileReader,x=!1;U.onload=function(h){!(h=h.target.result)||svGlobal.rdpFile.loadRdpFile(h,t)||x||(x=!0,U.readAsText(z))};U.readAsText(z,
"UTF-16LE")}else hi5.notifications.notify({msg:"Sorry, Please .rdp file only"})}}};
function initDragDrop(h,t){function z(h){svGlobal.rdpFile.handleFiles(h.target.files,t)}if("FileReader"in window){var C=h.style.backgroundColor,I=hi5.$("rdpfile");I&&I.addEventListener("change",z,!1);h.addEventListener("dragover",function(t){cancelDefault(t);h.style.backgroundColor="yellow"},!1);h.addEventListener("dragleave",function(t){cancelDefault(t);h.style.backgroundColor=C},!1);h.addEventListener("drop",function(z){cancelDefault(z);h.style.backgroundColor=C;svGlobal.rdpFile.handleFiles(z.dataTransfer.files,
t)},!1)}}svGlobal.util.initDragDrop=initDragDrop;
svGlobal.util.initMapDisk=svGlobal.util.MapDisk=function(h,t,z){function C(x){cancelDefault(x);t&&("0.6"!=h.style.opacity&&(h.style.opacity="0.6"),h.style.backgroundColor="yellow")}function I(x){cancelDefault(x);t&&(h.style.opacity=h.__oldOpacity,h.style.backgroundColor=h.__oldColor)}function U(x){cancelDefault(x);if(t){h.style.opacity=h.__oldOpacity;h.style.backgroundColor=h.__oldColor;var C=hi5.file.getEntries(x);!C.length||"file:"==location.protocol&&!hi5.browser.isElectron&&hi5.browser.isChrome?
t.addFiles?t.addFiles(x.dataTransfer.files,z):t.addFile(x.dataTransfer.files[0]):hi5.file.getFilesFromEntries(C,function(h){t.addFiles?t.addFiles(h,z):t.addFile(h[0])})}}"FileReader"in window&&(h.__oldColor=h.style.backgroundColor,h.__oldOpacity=h.style.opacity,h.addEventListener("dragover",C,!1),h.addEventListener("dragleave",I,!1),h.addEventListener("drop",U,!1),this.release=function(){h.removeEventListener("dragover",C,!1);h.removeEventListener("dragleave",I,!1);h.removeEventListener("drop",U,
!1);h=t=null})};
svGlobal.util.getServerArgs=function(h){var t=window.opener;if(!h)try{t&&t.__sparkUser&&t.__sparkUser.server&&(h=t.__sparkUser.server),!h&&t.sparkServer&&(h=t.sparkServer)}catch(z){}h?(t=h.rdp||h.vnc||h.ssh||h.telnet||null)&&!h.server&&(t.gateway=h.gateway,t.session=h.session,t.account=h.account,t.server=h.id,t.displayName=h.displayName,t.shadowing=h.shadowing,t.user=t.username||"",t.pwd=t.password||"",t.useConsole=t.console||!1,t.server_bpp=t.color,t.legacyMode=t.leagacyMode||t.legacyMode||!1,t.exe=
t.remoteProgram||"",t.args=t.remoteArgs||"",t.startProgram=0<t.exe.length?"app":t.command&&0<t.command.length?"shell":"noapp",h.keyboard&&(t.keyboard=h.keyboard),h=t):h=hi5.browser.cookie2Obj();return h};(function(){function h(t){t=document.getElementsByClassName("ver");for(var z=t.length,C=0;C<z;C++)t[C].innerHTML=svGlobal.version;window.removeEventListener("load",h,!1)}window.addEventListener("load",h,!1)})();svGlobal.logger.info("ver:"+svGlobal.version);
