var svManager={getInstance:function(){var r=window.$telnet;return r&&r.running&&r.running()?r:null}};function connvertServer(r){var v={};v.id=r.id;v.server=r.id;v.displayName=r.displayName||r.id;if(r=r.vnc)for(var z in r)v[z]=r[z];return v}
svGlobal.TELNET=function(r,v,z){function Ma(a,b){var d=[],e=null,c=new hi5.graphic.Rectangle(0,0,0,0),f="Uint8ClampedArray"in window;this.width=a;this.height=b;var m=!1,g=this;this.pause=function(a){m=a};this.release=function(){d=e=g=null};this.isPaused=function(){return m};this.setContext=function(a){a!=e&&(e||!a||a.createImageData(1,1).data.buffer||(f=!1),e=a)};this.getContext=function(){return e};this.resize=function(e,c){for(var m=0;m<c;m++)d[m]=new Uint32Array(e);g.width=a=e;g.height=b=c};g.resize(a,
b);this.getBuffer=function(){return d};this.setRGB=function(a,b,e){d[b][a]=e|4278190080};this.getRGB=function(a,b){return d[b][a]};this.setRGBs=function(a,b,e,c,m,f,g){e=a+e;c=b+c;for(var h=d,k,l=b;l<c;l++,f+=g){var Na=f;k=h[l];for(b=a;b<e;b++)k[b]=m[Na++]}};this.moveArea=function(a,b,e,c,m,f){if(0<f){m=a+m;f=b+f;var g=d,h;for(h=c-1;0<=h;h--){var k=g[f+h];var l=g[b+h];for(c=0;c<e;c++)k[m+c]=l[a+c]}}else if(0>f){m=a+m;f=b+f;var g=d;for(k=0;k<c;k++){l=g[f+k];var n=g[b+k];for(h=0;h<e;h++)l[m+h]=n[a+
h]}}else if(0<m)for(m=a+m,f=b+f,g=d,--e;0<=e;e--)for(k=m+e,l=a+e,h=0;h<c;h++)g[f+h][k]=g[b+h][l];else for(m=a+m,f=b+f,g=d,h=0;h<e;h++)for(l=m+h,n=a+h,k=0;k<c;k++)g[f+k][l]=g[b+k][n]};this.getRGBs=function(a,b,e,c){var m=_Uint32Array(e*c);m[0]=0;var f=d;e=a+e;c=b+c;for(var h=0,g=b;g<c;g++)for(b=a;b<e;b++)m[h++]=f[g][b];return m};this.repaint=function(c,m,g,h){if(e){0>c&&(g+=c,c=0);0>m&&(h+=m,m=0);c+g>a&&(g=a-c);m+h>b&&(h=b-m);var k=e.createImageData(g,h),l=k.data;g=c+g;h=m+h;var n=0,r=d;if(f)for(var l=
new Uint32Array(l.buffer),p,q=m;q<h;q++)for(p=c;p<g;p++)l[n++]=r[q][p];else for(var t,u,q=m;q<h;q++)for(p=c;p<g;p++)t=r[q][p],u=n<<2,l[u]=t&255,l[u+1]=t>>8&255,l[u+2]=t>>16&255,l[u+3]=255,n++;e.putImageData(k,c,m)}};this.postPaint=function(a,b,e,m){0<c.width?c.union(a,b,e,m):(c.x=a,c.y=b,c.width=e,c.height=m)};this.commitPaint=function(){0<c.width&&(this.repaint(c.x,c.y,c.width,c.height),c.width=0)};this.fillRect=function(a,b,e,c,m){var g=d;e=a+e;c=b+c;for(var f=b;f<c;f++)for(b=a;b<e;b++)g[f][b]=
m}}function ya(a,b){N?N.resize(a,b):N=new Ma(a,b);return N}function za(){var a=r.indexOf("://"),b=r.substring(a+3),a=b.indexOf("/");0<a&&(b=b.substring(0,a));return location.protocol+"//"+b}function Oa(a){return ea?hi5.browser.httpGet(za()+"/CLIP?s="+ea+"&t="+(new Date).getTime(),!1):""}function ka(a){return"on"==a||"true"==a}function Aa(a,b,d){this.need=a;this.handler=b;this.repeat=d||1}function Pa(){if(!B){Ba();if(la)p=la;else{var a=hi5.tool.replaceQuery(r,"pwd","x");hi5.browser.binaryWS()&&(a+=
"&binary=on");var b=window.opener;if(b){var d=null;try{d=b.__sparkUser}catch(e){}d&&(b=d.account,d=d.session,b&&(a+="&account="+b),d&&(a+="&session="+d))}a=f.modifyURL(a+("&pasteCap="+(hi5.browser.isChrome&&hi5.browser.isDesktop?3:0)));(d=hi5.browser.cookie.get("__SV_TOKEN_A"))&&(a+="&__SV_TOKEN_A="+encodeURIComponent(d));p=new WebSocket(a,"telnet");p.binaryType="arraybuffer"}I.ws=p;svGlobal.logger.info(r);p.onopen=Qa;void 0!=k.recording&&"on"==k.recording&&Ra(k);p.onmessage=function(a){a=a.data;
if("string"!=typeof a){var b=new Uint8Array(a);null!=O&&O.add(new RecordingObj(b,0,a.byteLength));Y.set(b,0,a.byteLength);Y.handle()}else{var e=parseInt(a.substring(0,2),16),b=a.substring(2);switch(e){case 15:JSON.parse(b);if(f){if(f.onready)f.onready();if(f.onloggedin)f.onloggedin()}break;case 26:a=JSON.parse(b);if(a.name){svGlobal.logger.info("msg="+b);if(f.onerror)f.onerror(a);b=__svi18n.errorCode["S"+a.name]||"";b+=a.message;f.showMessage(b)}else 0<svGlobal.log&&console.erro("No error code for message:"+
b);break;case 27:0!=D.drawLicense&&(x.drawLicense(b),ma(k.fontSize));break;case 56:a=JSON.parse(b);ea=a.session;a.server=f.server;if(b=hi5.$("joinSelect"))b.value=a.joinMode;if(b=hi5.$("requestControl"))b.disabled=a.hasControl;var b=D.page&&D.page.joinssh||"jointelnet.html",b=location.protocol+"//"+location.host+"/"+b+"?id="+a.numericId,b=f.modifyURL(b),m=a.webAddress;m&&0<m.length&&(e=m.indexOf("://"),m=m.substring(e+3),e=m.indexOf("/"),0<e&&(m=m.substring(0,e)),m.toLowerCase()!=location.host.toLowerCase()&&
(b+="&gateway="+m));a.joinLink=b;f.sessionInfo.appInfo=a;a.ver&&a.ver!=svGlobal.version&&svGlobal.logger.warn("Client:"+svGlobal.version+" server:"+a.ver);if(f.onsessionstart)f.onsessionstart(f.sessionInfo);break;case 59:a=hi5.Base64.dec(b,0);na=a[3]<<24|a[2]<<16|a[1]<<8|a[0];na&64&&f.showMessage(__svi18n.info.recording);x.setFeature(na);break;case 61:a=JSON.parse(b);switch(a.type){case 0:k.fontSize=parseInt(a.fontSize);v=a.width;z=a.height;Ba();x.setAutoScale(!0);fa(v+y,z+y);a.server&&(f.server=
a.server,f.setTitle&&(document.title=k.displayName||f.server));Ca=a.length;if(f.onopened)f.onopened(a);break;case 1:a=a.duration;if(f.onprogress)f.onprogress(a,Ca);break;case 2:2==a.status?B=!0:(b=0==a.status,N.pause(b),a.warn&&f.showMessage(b?__svi18n.info.sessionPaused:__svi18n.info.sessionResumed))}break;case 62:Sa(b);break;default:svGlobal.logger.warn("@TODO:"+a+"\n")}}};p.onclose=ga;p.onerror=Ta;fa(v+y,z+y)}}function Ra(a){O=new RecordingManager;O.setHeader({name:a.server,width:a.width,height:a.height,
color:a.fontSize,namesuffix:".telnetv",filetag:"TELV",duration:0})}function Ua(a,b){var d=0,e=!1;this.width=a;this.interval=b;var c=0;this.start=function(){e||(e=!0,d=setInterval(function(){if(x&&B){var b=x.getThumbnail(a);b&&b.length!=c&&(p.send("8E7"+b),c=b.length)}},b))};this.stop=function(){clearInterval(d)}}function Va(a,b){!L||L.width==a&&L.interval==b||(L.stop(),L=null);L||(L=new Ua(a,b));L.start()}function Sa(a){var b=parseInt(a.substring(0,1),16),d=a.substring(1);a=!1;var e=f.sessionInfo.appInfo;
switch(b){case 1:var c=JSON.parse(d);f.onsessionjoin&&(a=f.onsessionjoin(c));if(a)break;f.showMessage(__svi18n.info.joinsession.applyArgs([c.numericId,c.__ip,c.name]));break;case 2:c=JSON.parse(d);f.onsessionexit&&(a=f.onsessionexit(c));if(a)break;f.showMessage(__svi18n.info.exitsession.applyArgs([c.numericId,c.__ip,c.name]));break;case 3:c=JSON.parse(d);e.joinMode!=c.mode&&(e.joinMode=c.mode,b=hi5.$("joinSelect"))&&(b.value=c.mode);if(e.hasControl)break;x.setReadOnly(!1);if(b=hi5.$("requestControl"))b.disabled=
!0;f.ongivecontrol&&(a=f.ongivecontrol());if(a)break;f.showMessage(__svi18n.info.givecontrol);break;case 4:x.setReadOnly(!0);e.hasControl=!1;if(b=hi5.$("requestControl"))b.disabled=!1;f.ontakebackcontrol&&(a=f.ontakebackcontrol());if(a)break;f.showMessage(__svi18n.info.nocontrol);break;case 5:c=JSON.parse(d);f.onrequirecontrol&&(a=f.onrequirecontrol(c));if(a)break;a=__svi18n.info.title.applyArgs([c.name,c.numericId,c.__ip]);hi5.notifications.notify({title:a,msg:__svi18n.info.recontrol,cbYes:function(){f.giveControl(c.numericId);
this.destroy()},cbNo:function(){f.refuseControl(c.numericId);this.destroy()}});break;case 6:x.setTouchRemoting(!0);break;case 7:c=JSON.parse(d);c.cols&&c.rows&&(a=t*c.cols+2*y,b=h*c.rows+2*y,N=ya(a,b),fa(a,b));break;case 8:c=JSON.parse(d);if(f.onrequestcredential&&f.onrequestcredential(c))break;x.requestCredential(c);break;case 9:c=JSON.parse(d);0<c.interval&&0<c.width?Va(c.width,c.interval):L&&(L.stop(),L=null);break;case 11:c=JSON.parse(d),f.onrequirejoin&&(a=f.onrequirejoin(c)),a||(a=__svi18n.info.title.applyArgs([c.name,
c.numericId,c.__ip]),hi5.notifications.notify({title:a,msg:__svi18n.info.reqjoin,cbYes:function(){f.allowJoin(c.numericId,!0);this.destroy()},cbNo:function(){f.allowJoin(c.numericId,!1);this.destroy()}}))}}function Qa(a){svGlobal.logger.info("opened...");B=!0;p.send("87"+navigator.userAgent);if(f.onopen)f.onopen()}function Ta(a){svGlobal.logger.warn(a)}function ga(a){svGlobal.logger.warn("closed ...");Q&&(Q.style.display="none");oa=B=!1;if(f&&f.onclose)f.onclose();try{null!=O&&(O.exit(),O=null),x&&
x.close(),T&&T.visible()&&(T.dismiss(),T=null)}catch(b){}Y&&(Y.release(),Y=null);R=g=null;p&&(p.onopen=null,p.onmessage=null,p.onclose=null,p=p.onerror=null);f=x=I=null;window&&window.$telnet&&(window.$telnet=null);null!=O&&(O.exit(),O=null)}function ma(a,b){b||(b=J);g.font=a+"px "+b;t=g.measureText("X").width;W=parseInt(z/h);E=parseInt(v/t);pa(parseInt(z/h))}function pa(a,b){b&&(S=b);a&&(P=a,ha=(P-1)*h+u);Da=1==S&&P==Math.floor(z/h)}function fa(a,b){var d=a-y,e=b-y,c=Math.floor(e/h),f=Math.floor(d/
t),m=null;B&&(m=g.getImageData(0,0,Math.min(f*t+y,E*t+y),Math.min(c*h+y,W*h+y)));v=d;z=e;x.setSize(a,b);ma(k.fontSize);qa();m&&g.putImageData(m,0,0);W=c;E=f;pa(Math.floor(z/h))}function Ba(){Q||(qa(),n=q,l=u,10>k.fontSize&&(k.fontSize=10),12>=k.fontSize?(h=k.fontSize+6,da=2):13<=k.fontSize&&18>k.fontSize?(h=k.fontSize+8,da=2):19<=k.fontSize&&25>k.fontSize?(h=k.fontSize+12,da=3):25<=k.fontSize&&(h=k.fontSize+16,da=4),ma(k.fontSize),remotectrl.style.cursor="text",Q=document.getElementById("cursorID"),
Q.style.display="block",Q.style.width=t+"px",Q.style.height=h+"px",oa=!0)}function qa(){g.fillStyle=C;g.fillRect(0,0,R.width,R.height);g.fillStyle=F}function Ea(a){if(0!=w||ra[a])""!=M&&sa(M),Wa(a);else if(ta){var b=G[a]||"";M=""!=b?M+b:M+String.fromCharCode(a)}else M=127<a&&256>a?M+G[a]:M+String.fromCharCode(a)}function ua(a){for(;;){var b=a.getByte();if(255==b&&(b=a.getByte(),240==b))break}}function Z(a,b,d){p.send("D5"+a+"\t"+b+"\t"+(1==d?1:0));251==a?va(b):252==a?va(b):253==a?wa(b):254==a&&wa(b)}
function va(a){return 39>=a&&0<=a&&Xa[a-0]}function wa(a){return 39>=a&&0<=a&&Ya[a-0]}function Wa(a){switch(a){case 0:case 24:return w=0,!1;case 26:return w=0,!1;case 5:return!1;case 7:return!1;case 8:return n-=t,n<q&&(n=q),A(),!1;case 9:var b=(n-q)/t/8,b=parseInt(1*b)+1;n=8*b*t+q;n>=E*t&&(n=q,l+=h,aa("\n"));A();return!1;case 13:return n=q,l>u+(P-1)*h&&(l=u+(P-1)*h),A(),!1;case 10:case 11:case 12:return Fa(),!1;case 15:return!1;case 14:return!1;case 17:case 19:return!1;case 27:return U="",w=27,!1;
default:if(128<=a&&159>=a)return!1}switch(w){case 0:return!0;case 27:if("\\"==a)return!1;if(32<=a&&47>=a)return U+=String.fromCharCode(a),!1;if(32<=a&&126>=a||160<=a){null==U&&(U="");switch(a){case 48:"("==U&&(ta=!0);break;case 65:l-=h;A();break;case 66:"("==U&&(ta=!1);break;case "C":n+=t;A();break;case 68:""==U&&Ga(1);A();break;case 72:n=q;l+=h;break;case 77:""==U&&Ha(1);break;case "P":w=0;w=144;break;case "Y":w=161;break;case "c":w=0;break;case 91:V="";w=0;w=155;break;case 93:w=0;w=157;break;case "^":w=
0,w=158}27==w&&(w=0);return!1}return!0;case 155:if(48<=a&&63>=a||32<=a&&47>=a)return V+=String.fromCharCode(a),!1;if(32<=a&&126>=a||160<=a){b=null;null==V&&(V="");""!=V&&(b=V.split(";"));switch(a){case 65:var d=null!=b&&1<=b.length?parseInt(b[0]):1;l-=d*h;l<u&&(l=u);A();break;case 66:d=null!=b&&1<=b.length?parseInt(b[0]):1;a=l;l+=d*h;a=(l-a)/h;aa("\n",0==a?1:a);A();break;case 67:b=null!=b&&1<=b.length?parseInt(b[0]):1;n+=b*t;A();break;case 68:b=null!=b&&1<=b.length?parseInt(b[0]):1;n-=b*t;n<q&&(n=
q);A();break;case 69:d=null!=b&&1<=b.length?parseInt(b[0]):1;a=l;l+=d*h;a=(l-a)/h;aa("\n",0==a?1:a);n=q;A();break;case 70:d=null!=b&&1<=b.length?parseInt(b[0]):1;l-=d*h;l<u&&(l=u);n=q;A();break;case 72:case 102:null!=b?(1<=b.length&&(d=parseInt(b[0]),a=l,l=u+(d-1)*h,a=(l-a)/h,aa("\n",0==a?1:a)),2<=b.length&&(b=parseInt(b[1])-1,n=q+b*t)):""==V&&(n=q,l=u);break;case 73:b=1<=b.length?parseInt(b[0]):1;n=q+8*b*t;break;case 74:null!=b&&1<=b.length?(b=parseInt(b[0]),1==b?(g.fillStyle=C,g.fillRect(q,u,E*
t,l-chart_height-u),g.fillRect(q,l,l-q,chart_height),g.fillStyle=F):2==b&&(qa(),n=q,l=u)):(g.fillStyle=C,g.fillRect(n,l,E*t-n+q,W*h-l+u),g.fillStyle=F);break;case 75:null!=b&&1<=b.length?(b=parseInt(b[0]),1==b?xa(q,n):2==b&&xa(q,v+y),A()):xa(n,v+y);break;case 76:null!=b&&1<=b.length&&(d=parseInt(b[0]),Ha(d),A());break;case 77:null!=b&&1<=b.length&&(d=parseInt(b[0]),Ga(d),A());break;case 80:b=null!=b&&1<=b.length?parseInt(b[0]):1;b=g.getImageData(n+b*t,l,v+y-n-b*t,h);g.fillStyle=C;g.fillRect(n,l,v+
y-n,h);g.putImageData(b,n,l);g.fillStyle=F;A();break;case 88:b=null!=b&&1<=b.length?parseInt(b[0]):1;g.fillStyle=C;g.fillRect(n,l,b*t,h);g.fillStyle=F;break;case 109:if(null==b||0==b.length)g.font="normal "+k.fontSize+"px "+J,F=k.fgColor||H[7],C=k.bgColor||H[0];else{a=b.length;for(var e=0;e<a;e++)switch(d=1*b[e],d){case 0:g.font="normal "+k.fontSize+"px "+J;C=H[0];F=H[7];break;case 1:g.font="bold "+k.fontSize+"px "+J;break;case 4:break;case 5:g.font="italic "+k.fontSize+"px "+J;break;case 7:g.font=
"normal "+k.fontSize+"px "+J;C=H[7];F=H[0];break;case 22:g.font="normal "+k.fontSize+"px "+J;C=H[0];F=H[7];break;case 24:break;case 25:g.font="italic "+k.fontSize+"px "+J;break;case 27:g.font="normal "+k.fontSize+"px "+J;C=H[7];F=H[0];break;default:30<=b[e]&&39>=b[e]?F=H[b[e]-30+1]:40<=b[e]&&49>=b[e]&&(C=H[b[e]-40+1])}}break;case 114:null!=b&&2<=b.length&&(a=parseInt(b[0]),b=parseInt(b[1]),pa(b,a))}w=0;return!1}return!0;case 144:case 157:case 158:case 159:return 48<=a&&63>=a||32<=a&&47>=a?!1:32<=
a&&126>=a||160<=a?(w=160,!1):!0;case 160:return 32<=a&&126>=a||160<=a?!1:!0;case 161:return w=162,!1;case 162:return w=0,!1;default:return w=0,!1}}function xa(a,b){g.fillStyle=C;g.fillRect(a,l,b-a,h);g.fillStyle=F}function Ha(a){var b=g.getImageData(q,u+(S-1)*h,E*t,(P-S-a+1)*h);g.fillStyle=C;g.fillRect(q,u+(S-1)*h,E*t,h*a);g.putImageData(b,q,u+(S+a-1)*h);g.fillStyle=F}function Ga(a){var b=g.getImageData(q,(S+a-1)*h+u,E*t,(P-S-a+1)*h);g.fillStyle=C;g.fillRect(q,(P-a)*h+u,E*t,a*h);g.putImageData(b,
q,(S-1)*h+u);g.fillStyle=F}function Fa(){l+=h;aa("\n");A();Ia()}function Ia(){n>=E*t&&(n=q,l+=h);if(l>ha){for(;l>ha;)l-=h;A();if(Da){var a=R.height-(u+h);g.drawImage(R,0,u+h,R.width,a,0,u,R.width,a);g.fillStyle=C;g.fillRect(0,ha,R.width,h)}else a=g.getImageData(q,u+h,E*t,(P-1)*h),g.fillStyle=C,g.fillRect(q,u,E*t,P*h),g.putImageData(a,q,u);g.fillStyle=F}}function sa(a){var b=a.length,d=((n-q)/t|0)+b-E;0<d?(b-=d,Ja(a.substring(0,b),b),Ia(),sa(a.substring(b))):(Ja(a,b),"--More--"==a.trim()&&Fa())}function Ja(a,
b){l+h>z&&(l=(W-1)*h+u);g.fillStyle=C;g.fillRect(n,l,t*b,h);g.fillStyle=F;g.fillText(a,n,l+h-3*da);n+=g.measureText(a).width;aa(a);A();M=""}function A(){Q.style.top=l+"px";Q.style.left=n+"px"}function Za(a){if(B)return(a=a.getData("text/plain"))?(a=a.replace(/\r\n/g,"\n"),ba(a),!0):!1}function $a(){T&&ca&&!T.visible()&&(ca.value=X,T.show(),x&&x.setIgnorePaste(!1),setTimeout(function(){ca.scrollTop=ca.scrollHeight;ca.disabled=!1},10))}function aa(a,b){if(T){if(b)for(var d=0;d<b;d++)X+=a;else X+=a;
1E5<X.length&&(X=X.substring(4E4))}}function ba(a){if(a){var b=a.length+1,d=new Uint8Array(b);d[0]=147;for(var e=1;e<b;e++)d[e]=a.charCodeAt(e-1);p.send(d.buffer)}}sessionStorage&&sessionStorage.clear();var ca=document.getElementById("copytextarea"),T=ca?new hi5.Lightbox(document.getElementById("copydialog")):null,X="";this.displayMsg=!0;this.reconnectTimes=0;this.setTitle=this.openLink=!0;this.mode=0;var la="object"==typeof r?r:null,Ka="object"==typeof r||0<r.indexOf("/PLAY?");Ka?(this.mode=1,la&&
(r=""),r+="&touchpad=on"):0<r.indexOf("/JOIN?")&&(this.mode=2,this.reconnectOnResize=!1);var D=hi5.appcfg||{img:{},toolbar:{fadable:!0}};this.sessionInfo={major:0,minor:0,width:0,height:0,bpp:0,bigEndian:!0,trueColor:!0};var ea="",x=null,B=!1,oa=!1,na=0,y=5,O=null;window.$telnet=this;D.copyDialog=!0;for(var G=[],K=0;127>K;K++)G[K]=String.fromCharCode(K);G[106]="+";G[107]="+";G[108]="+";G[109]="+";G[110]="+";G[113]="_";G[116]="+";G[117]="+";G[118]="+";G[119]="+";G[120]="|";(function(){for(var a={128:199,
129:252,130:233,131:226,132:228,133:224,134:229,135:231,136:234,137:235,138:232,139:239,140:238,141:236,142:196,143:197,144:201,145:230,146:198,147:244,148:246,149:242,150:251,151:249,152:255,153:214,154:220,155:162,156:163,157:165,158:8359,159:402,160:225,161:237,162:243,163:250,164:241,165:209,166:170,167:186,168:191,169:8976,170:172,171:189,172:188,173:161,174:171,175:187,176:9617,177:9618,178:9619,179:9474,180:9508,181:9569,182:9570,183:9558,184:9557,185:9571,186:9553,187:9559,188:9565,189:9564,
190:9563,191:9488,192:9492,193:9524,194:9516,195:9500,196:9472,197:9532,198:9566,199:9567,200:9562,201:9556,202:9577,203:9574,204:9568,205:9552,206:9580,207:9575,208:9576,209:9572,210:9573,211:9561,212:9560,213:9554,214:9555,215:9579,216:9578,217:9496,218:9484,219:9608,220:9604,221:9612,222:9616,223:9600,224:945,225:223,226:915,227:960,228:931,229:963,230:181,231:964,232:934,233:920,234:937,235:948,236:8734,237:966,238:949,239:8745,240:8801,241:177,242:8805,243:8804,244:8992,245:8993,246:247,247:8776,
248:176,249:8729,250:183,251:8730,252:8319,253:178,254:9632,255:160},b=128;256>b;b++)G[b]=String.fromCharCode(a[b])})();for(var Ya=[!0,!0,!1,!0,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1],Xa=[!0,!1,!1,!0,!1,!1,!1,!1,!1,!1,!1,!1,!0,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!0,!1,!1,!1,!1,!1,!1,!0,!0,!1,!1,!1,!1,!1,!1,!1,!1],ra=Array(256),ia=[0,5,7,8,9,10,11,12,13,14,15,17,19,24,26,27,127,132,133,136,141,142,143,144,146,155,156,157,158,159],
K=0;256>K;K++)ra[K]=!1;for(K=0;K<ia.length;K++)ra[ia[K]]=!0;var Y=new function(a){var b=0,d=0,e=new Uint8Array(a),c=this,f=new Aa(0,null,0);this.release=function(){c=e=f=null};this.getHandler=function(){return f};this.getData=function(){return e};this.getPosition=function(){return b};this.setPosition=function(a){b=a};this.getEnd=function(){return d};this.set=function(a,c,f){e=a;b=c;d=f};this.handle=function(){f.handler(c,f)};this.setHandler=function(a){a&&1>a.need&&svGlobal.logger.warn("need < 1");
(f=a)&&d-b>=a.need&&a.handler(c,a)};this.getByte=function(){return e[b++]};this.peekByte=function(){return e[b]};this.getBE32=function(){return e[b++]<<24|e[b++]<<16|e[b++]<<8|e[b++]};this.getBE16=function(){return e[b++]<<8|e[b++]};this.skip=function(a){b+=a};this.skipBack=function(a){b-=a};this.getBytes=function(a,c){if(c)for(var d=0;d<a;d++)c[d]=e[b++];else return d=b,b+=a,e.subarray(d,b)};this.copyToByteArray=function(a,b,c,d){hi5.Arrays.arraycopy(e,c,a,b,d)}}(4194304);this.running=function(){return B};
this.getHistory=function(){return X};var f=this,p=null,k=hi5.tool.queryToObj(r.substring(r.indexOf("?")+1));v||(v=window.innerWidth);v-=y;k.width=v;r+="&width="+v;z||(z=window.innerHeight);z-=y;k.height=z;r+="&height="+z;k.fontSize?k.fontSize=parseInt(k.fontSize,10):(k.fontSize=13,r+="&fontSize=13");this.server=k.server;this.port=k.port?parseInt(k.port,10):23;this.loadbalanceToken=D.loadbalanceTokenName?D.loadbalanceTokenName+"="+hi5.tool.uuid():"";this.modifyURL=function(a){f.loadbalanceToken&&(a+=
"&"+f.loadbalanceToken);return a};var H="black red green yellow blue magenta cyan white gray violet".split(" "),N=ya(v,z),g=N.getContext(),R,I=new function(){this.ws=null;this.setJoinMode=f.setJoinMode;this.requestControl=f.requestControl;this.writeKeyComb=f.writeKeyComb;this.localLockFlags=0;this.checkLockFlags=!0;this.getAppMode=function(){return f.mode};this.send=function(a){"891"!=a&&B&&this.ws.send(a)};this.sendInput=function(a){f.writeRawInput(a);if(f.onactivity)f.onactivity(a)};var a=null;
this.getAppInfo=function(){return f.sessionInfo.appInfo};this.onresize=function(b){if(b=b.target.svSurface){b=b.getFreeSpace();var d=b.width,e=b.height;hi5.browser.isTouch||hi5.browser.isOpera||!B||(a&&(clearTimeout(a),a=null),a=setTimeout(function(){fa(d,e);p.send("D9"+E+"\t"+W)},200))}};this.onorientationchange=function(a){};this.getClipData=Oa;this.onfocus=function(a){};this.fileCallback=[];this.getShareFiles=function(a,d){loggedin&&(this.ws.send("3A5"+a),this.fileCallback.push(d))};this.notifyFiles=
function(a){for(var b=this.fileCallback,e=0,c=b.length;e<c;e++)b[e](a)};this.getFile=function(a){window.open(f.getFileUrl(a))};this.removeFile=function(a){uploadMgr&&uploadMgr.fileService.remove(a)};this.getFileLink=function(a){return za()+"/DOWNLOAD?s="+ea+"&f="+a};this.getGateway=function(){return r};this.reconnect=function(a,d,e){};this.sendKeyboardSyncFlags=function(a){return B?(this.remoteLockFlags=this.localLockFlags=a,!0):!1}};void 0!=D.displayMsg&&(this.displayMsg=D.displayMsg);void 0!=D.reconnectTimes&&
(this.reconnectTimes=D.reconnectTimes);void 0!=D.openLink&&(this.openLink=D.openLink);void 0!=D.setTitle&&(this.setTitle=D.setTitle);"boolean"==typeof D.useWSS&&(r=(D.useWSS?"wss":"ws")+r.substring(r.indexOf("://")));this.getURL=function(){return r};this.setJoinMode=function(a){B&&p.send("8E1"+a)};this.refuseControl=function(a){B&&p.send("8E3"+a)};this.giveControl=function(a){B&&p.send("8E4"+a)};this.requestControl=function(){B&&p.send("8E2")};this.play=function(){p.send("F3")};this.pause=function(){p.send("F2")};
this.scan=function(a){p.send("F4"+(a?"1":"0"))};this.seek=function(a){x&&B&&(p.send("F4"+(a?"1":"0")+"\t"+(a/x.getScale()|0)),N.pause(!0))};var L=null,Ca=0;this.run=function(){Pa()};this.hide=function(){x&&("block"==document.getElementById("cursorID").style.display&&(document.getElementById("cursorID").style.display="none"),x.hide())};this.showMessage=function(a){f.displayMsg&&a&&hi5.notifications.notify({msg:a})};this.close=function(){if(p&&B)try{p.send("85"),p.close()}catch(a){}else ga()};hi5.browser.isChromeApp?
chrome.runtime.onSuspend.addListener(ga):window.addEventListener("unload",ga,!1);var La=!1,Q=null,q=y=5,u=5,n=0,l=0,J=k.fontName||"Courier New";0<J.indexOf(" ")&&(J='"'+J+'"');var F=k.fgColor||H[7],C=k.bgColor||H[0],w=0,V="",U="",t=0,h=18,da=0,M="",ta=!1,W=0,E=0,S=1,P=24,ha=0,Da=!0,ia=new Aa(1024,function(a){for(var b=!0,d;b;){d=a.getByte();if(0>d)break;if(255==d)a:{var e=a,c=e.getByte();switch(c){case 255:Ea(c);break;case 254:case 253:case 252:case 251:d=e.getByte();e=c;253!=e||va(d)?251!=e||wa(d)?
254==e?Z(252,d,!1):252==e?Z(254,d,!1):253==e?(Z(251,d,!1),31==d?p.send("D9"+E+"\t"+W):12==d&&p.send("D7")):251==e&&Z(253,d,!1):Z(254,d,!0):Z(252,d,!0);break;case 250:d=e.getByte();switch(d){case 24:d=e.getByte();ua(e);if(1!=d)break;p.send("DA");break;case 32:d=e.getByte();ua(e);if(1!=d)break;p.send("DC");break;default:ua(e)}break;default:break a}La||(La=!0,p.send("D0"))}else Ea(d);a.getPosition()>=a.getEnd()&&(""!=M&&sa(M),b=!1)}});Y.setHandler(ia);this.addSurface=function(a){x=a;Ka&&a.setPlayerMode();
N.setContext(x.context);g=N.getContext();R=g.canvas;a.forceTextArea=!0;a.setAutoScale(0<f.mode);a.setSize(v+y,z+y);a.setController(I);a.setFastCopy(ka(k.fastCopy));a.setTouchpad(ka(k.touchpad));a.setClipboard(ka(k.mapClipboard));a.run(99997,!1,!0);a.onclipdata=Za};this.writeText=ba;this.writeScancode=function(a,b){ba(ja.process(a,b,0))};var ab={" ":57,space:57,pageup:201,pagedown:209,end:207,home:199,left:203,up:200,right:205,down:208,printscreen:183,insert:210,del:211,"delete":211,altgr:184,windows:219,
windowsright:220,context:221,esc:1,backspace:14,tab:15,enter:28,meta:29,command:29,ctrl:29,shift:42,alt:56,capslock:58,f1:59,f2:60,f3:61,f4:62,f5:63,f6:64,f7:65,f8:66,f9:67,f10:68,f11:87,f12:88,numlock:69,scrolllock:70,add:78};this.writeKeyComb=function(a){a=a.split("+");var b=a.length;if(0!=b)for(var d=null,e=0;e<b;e++){var c=a[e];""==c&&""==d&&(c="Add");if(""!=c){var d=c,g=ab[d.toLowerCase()];g?f.writeScancode(!0,g):console.log("Invalid key:"+d)}d=c}};this.writeRawInput=function(a){if(oa){var b=
parseInt(a.substring(0,2),16);a=a.substring(2).split("\t");switch(b){case 128:2==a[2]&&$a();return;case 129:return;case 130:return;case 131:return;case 132:b=parseInt(a[1]);a=0==a[0];ba(ja.process(a,b,0));return;case 139:b=parseInt(a[1]);a=0==a[0];ba(ja.process(a,b,1));return;case 134:ba(ja.process(!0,a[0],3));return}svGlobal.logger.warn("Unknowncode: "+a[1]+" type:"+b)}};var ja=new function(a,b,d){var e=!1,c=!1,f=!1;this.process=function(a,b,d){if(3==d)return b;if(0==d){switch(b){case 29:case 157:return e=
a,"";case 56:case 184:return c=a,"";case 42:case 54:return f=a,""}if(a){switch(b){case 28:a="\r\n";break;case 200:a="\u001b[A";break;case 208:a="\u001b[B";break;case 205:a="\u001b[C";break;case 203:a="\u001b[D";break;case 59:a="\u001bOP";break;case 60:a="\u001bOQ";break;case 61:a="\u001bOR";break;case 62:a="\u001bOS";break;case 63:a="\u001b[15~";break;case 64:a="\u001b[17~";break;case 65:a="\u001b[18~";break;case 66:a="\u001b[19~";break;case 67:a="\u001b[20~";break;case 68:a="\u001b[21~";break;case 87:a=
"\u001b[23~";break;case 88:a="\u001b[24~";break;case 15:a="\t";break;case 209:a="\u001b[6~";break;case 201:a="\u001b[5~";break;case 199:a="\u001b[H";break;case 207:a="\u001b[F";break;case 14:a=f?"\b":"\u007f";break;case 211:a="\u001b[3~";break;case 197:a="\u00ff\u00f3";break;case 210:a="\u001b[2~";break;case 1:a="\u001b";break;case 55:a="*";break;case 71:a=I.localLockFlags&2?"7":"\u001b[H";break;case 72:a=I.localLockFlags&2?"8":"\u001b[A";break;case 73:a=I.localLockFlags&2?"9":"\u001b[5~";break;case 74:a=
"-";break;case 75:a=I.localLockFlags&2?"4":"\u001b[D";break;case 76:a="5";break;case 77:a=I.localLockFlags&2?"6":"\u001b[C";break;case 78:a="+";break;case 79:a=I.localLockFlags&2?"1":"\u001b[F";break;case 80:a=I.localLockFlags&2?"2":"\u001b[B";break;case 81:a=I.localLockFlags&2?"3":"\u001b[6~";break;case 82:a=I.localLockFlags&2?"0":"\u001b[2~";break;case 83:a=I.localLockFlags&2?".":"\u001b[3~";break;case 156:a="\r\n";break;case 181:a="/";break;default:return console.log("Invalid code:"+b),""}c&&(a=
"\u001b"+a);return a}return""}if(1==d&&e){if(64<b&&91>b)return String.fromCharCode(b-64);switch(b){case 54:return"\u001e";case 219:return"\u001b";case 220:return"\u001c";case 221:return"\u001d";case 32:return"\x00";case 192:return"\u001e";case 191:return"\u001f";default:return console.log("Invalid key code:"+b),""}}if(c)return"\u001b"+String.fromCharCode(b).toLowerCase()}}};
